class CityList{
 static List<String> cityNames = [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Mississauga",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Brampton",
    "Surrey",
    "Halifax",
    "Laval",
    "Markham",
    "Vaughan",
    "Gatineau",
    "Saskatoon",
    "Longueuil",
    "Kitchener",
    "Burnaby",
    "Windsor",
    "Regina",
    "Richmond",
    "Oakville",
    "Burlington",
    "Barrie",
    "Sherbrooke",
    "Saguenay",
    "Levis",
    "Abbotsford",
    "Coquitlam",
    "Trois-Rivieres",
    "St. Catharines",
    "Guelph",
    "Cambridge",
    "Whitby",
    "Kelowna",
    "Ajax",
    "Langley",
    "Saanich",
    "Terrebonne",
    "Milton",
    "St. John's",
    "Thunder Bay",
    "Waterloo",
    "Delta",
    "Chatham-Kent",
    "Red Deer",
    "Strathcona County",
    "Brantford",
    "Saint-Jean-sur-Richelieu",
    "Cape Breton",
    "Lethbridge",
    "Clarington",
    "Pickering",
    "Nanaimo",
    "Sudbury",
    "North Vancouver",
    "Brossard",
    "Repentigny",
    "Newmarket",
    "Chilliwack",
    "Maple Ridge",
    "Peterborough",
    "Kawartha Lakes",
    "Drummondville",
    "Saint-Jerome",
    "Prince George",
    "Moncton",
    "Sault Ste. Marie",
    "North Bay",
    "Medicine Hat",
    "Norfolk County",
    "Georgina",
    "Grande Prairie",
  ];

}