///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PrevRidesDataDataRecurringInstancesPreferencesOther {
/*
{
  "AppreciatesConversation": true,
  "EnjoysMusic": false,
  "SmokeFree": false,
  "PetFriendly": false,
  "WinterTires": false,
  "CoolingOrHeating": false,
  "BabySeat": false,
  "HeatedSeats": false
} 
*/

  bool? AppreciatesConversation;
  bool? EnjoysMusic;
  bool? SmokeFree;
  bool? PetFriendly;
  bool? WinterTires;
  bool? CoolingOrHeating;
  bool? BabySeat;
  bool? HeatedSeats;

  PrevRidesDataDataRecurringInstancesPreferencesOther({
    this.AppreciatesConversation,
    this.EnjoysMusic,
    this.SmokeFree,
    this.PetFriendly,
    this.WinterTires,
    this.CoolingOrHeating,
    this.BabySeat,
    this.HeatedSeats,
  });
  PrevRidesDataDataRecurringInstancesPreferencesOther.fromJson(Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
    EnjoysMusic = json['EnjoysMusic'];
    SmokeFree = json['SmokeFree'];
    PetFriendly = json['PetFriendly'];
    WinterTires = json['WinterTires'];
    CoolingOrHeating = json['CoolingOrHeating'];
    BabySeat = json['BabySeat'];
    HeatedSeats = json['HeatedSeats'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    data['EnjoysMusic'] = EnjoysMusic;
    data['SmokeFree'] = SmokeFree;
    data['PetFriendly'] = PetFriendly;
    data['WinterTires'] = WinterTires;
    data['CoolingOrHeating'] = CoolingOrHeating;
    data['BabySeat'] = BabySeat;
    data['HeatedSeats'] = HeatedSeats;
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesPreferences {
/*
{
  "luggageType": "S",
  "other": {
    "AppreciatesConversation": true,
    "EnjoysMusic": false,
    "SmokeFree": false,
    "PetFriendly": false,
    "WinterTires": false,
    "CoolingOrHeating": false,
    "BabySeat": false,
    "HeatedSeats": false
  }
} 
*/

  String? luggageType;
  PrevRidesDataDataRecurringInstancesPreferencesOther? other;

  PrevRidesDataDataRecurringInstancesPreferences({
    this.luggageType,
    this.other,
  });
  PrevRidesDataDataRecurringInstancesPreferences.fromJson(Map<String, dynamic> json) {
    luggageType = json['luggageType']?.toString();
    other = (json['other'] != null) ? PrevRidesDataDataRecurringInstancesPreferencesOther.fromJson(json['other']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['luggageType'] = luggageType;
    if (other != null) {
      data['other'] = other!.toJson();
    }
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesReturnTrip {
/*
{
  "isReturnTrip": false,
  "returnDate": null,
  "returnTime": null
} 
*/

  bool? isReturnTrip;
  String? returnDate;
  String? returnTime;

  PrevRidesDataDataRecurringInstancesReturnTrip({
    this.isReturnTrip,
    this.returnDate,
    this.returnTime,
  });
  PrevRidesDataDataRecurringInstancesReturnTrip.fromJson(Map<String, dynamic> json) {
    isReturnTrip = json['isReturnTrip'];
    returnDate = json['returnDate']?.toString();
    returnTime = json['returnTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isReturnTrip'] = isReturnTrip;
    data['returnDate'] = returnDate;
    data['returnTime'] = returnTime;
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesRecurringTrip {
/*
{
  "recurringTripDays": [
    1
  ],
  "recurringTripIds": [
    ""
  ],
  "isRecurringTripEnabled": false
} 
*/

  List<int?>? recurringTripDays;
  List<String?>? recurringTripIds;
  bool? isRecurringTripEnabled;

  PrevRidesDataDataRecurringInstancesRecurringTrip({
    this.recurringTripDays,
    this.recurringTripIds,
    this.isRecurringTripEnabled,
  });
  PrevRidesDataDataRecurringInstancesRecurringTrip.fromJson(Map<String, dynamic> json) {
  if (json['recurringTripDays'] != null) {
  final v = json['recurringTripDays'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    recurringTripDays = arr0;
    }
  if (json['recurringTripIds'] != null) {
  final v = json['recurringTripIds'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    recurringTripIds = arr0;
    }
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recurringTripDays != null) {
      final v = recurringTripDays;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripDays'] = arr0;
    }
    if (recurringTripIds != null) {
      final v = recurringTripIds;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripIds'] = arr0;
    }
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesStops {
/*
{
  "time": null,
  "name": "",
  "type": "Point",
  "coordinates": [
    0
  ],
  "originToStopFair": "",
  "stopToStopFair": "",
  "stopTodestinationFair": "",
  "_id": "67fca5fd8a71186dc7b8df2a"
} 
*/

  String? time;
  String? name;
  String? type;
  List<int?>? coordinates;
  String? originToStopFair;
  String? stopToStopFair;
  String? stopTodestinationFair;
  String? Id;

  PrevRidesDataDataRecurringInstancesStops({
    this.time,
    this.name,
    this.type,
    this.coordinates,
    this.originToStopFair,
    this.stopToStopFair,
    this.stopTodestinationFair,
    this.Id,
  });
  PrevRidesDataDataRecurringInstancesStops.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    coordinates = arr0;
    }
    originToStopFair = json['originToStopFair']?.toString();
    stopToStopFair = json['stopToStopFair']?.toString();
    stopTodestinationFair = json['stopTodestinationFair']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originToStopFair'] = originToStopFair;
    data['stopToStopFair'] = stopToStopFair;
    data['stopTodestinationFair'] = stopTodestinationFair;
    data['_id'] = Id;
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesDestination {
/*
{
  "name": "Whitby, ON, Canada",
  "type": "Point",
  "coordinates": [
    -78.9400809
  ]
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;

  PrevRidesDataDataRecurringInstancesDestination({
    this.name,
    this.type,
    this.coordinates,
  });
  PrevRidesDataDataRecurringInstancesDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class PrevRidesDataDataRecurringInstancesOrigin {
/*
{
  "name": "Oshawa, ON, Canada",
  "type": "Point",
  "coordinates": [
    -78.8635999
  ],
  "originDestinationFair": "5",
  "time": ""
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;
  String? originDestinationFair;
  String? time;

  PrevRidesDataDataRecurringInstancesOrigin({
    this.name,
    this.type,
    this.coordinates,
    this.originDestinationFair,
    this.time,
  });
  PrevRidesDataDataRecurringInstancesOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originDestinationFair = json['originDestinationFair']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originDestinationFair'] = originDestinationFair;
    data['time'] = time;
    return data;
  }
}

class PrevRidesDataDataRecurringInstances {
/*
{
  "_id": "67fca5fd8a71186dc7b8df29",
  "driverId": "67654c4898c6452c56f9a007",
  "origin": {
    "name": "Oshawa, ON, Canada",
    "type": "Point",
    "coordinates": [
      -78.8635999
    ],
    "originDestinationFair": "5",
    "time": ""
  },
  "destination": {
    "name": "Whitby, ON, Canada",
    "type": "Point",
    "coordinates": [
      -78.9400809
    ]
  },
  "stops": [
    {
      "time": null,
      "name": "",
      "type": "Point",
      "coordinates": [
        0
      ],
      "originToStopFair": "",
      "stopToStopFair": "",
      "stopTodestinationFair": "",
      "_id": "67fca5fd8a71186dc7b8df2a"
    }
  ],
  "tripType": "oneTime",
  "recurringTrip": {
    "recurringTripDays": [
      1
    ],
    "recurringTripIds": [
      ""
    ],
    "isRecurringTripEnabled": false
  },
  "date": "2025-04-19T00:00:00.000Z",
  "time": "2025-04-19T10:50:00.000Z",
  "returnTrip": {
    "isReturnTrip": false,
    "returnDate": null,
    "returnTime": null
  },
  "arrivalDate": null,
  "arrivalTime": null,
  "totalSeatAvailable": 3,
  "seatAvailable": 3,
  "preferences": {
    "luggageType": "S",
    "other": {
      "AppreciatesConversation": true,
      "EnjoysMusic": false,
      "SmokeFree": false,
      "PetFriendly": false,
      "WinterTires": false,
      "CoolingOrHeating": false,
      "BabySeat": false,
      "HeatedSeats": false
    }
  },
  "isStarted": false,
  "isCompleted": false,
  "isCancelled": false,
  "description": null,
  "endDateTime": "2025-04-14T06:06:53.744Z",
  "createdAt": "2025-04-14T06:06:53.790Z",
  "updatedAt": "2025-04-14T06:06:53.790Z"
} 
*/

  String? Id;
  String? driverId;
  PrevRidesDataDataRecurringInstancesOrigin? origin;
  PrevRidesDataDataRecurringInstancesDestination? destination;
  List<PrevRidesDataDataRecurringInstancesStops?>? stops;
  String? tripType;
  PrevRidesDataDataRecurringInstancesRecurringTrip? recurringTrip;
  String? date;
  String? time;
  PrevRidesDataDataRecurringInstancesReturnTrip? returnTrip;
  String? arrivalDate;
  String? arrivalTime;
  int? totalSeatAvailable;
  int? seatAvailable;
  PrevRidesDataDataRecurringInstancesPreferences? preferences;
  bool? isStarted;
  bool? isCompleted;
  bool? isCancelled;
  String? description;
  String? endDateTime;
  String? createdAt;
  String? updatedAt;

  PrevRidesDataDataRecurringInstances({
    this.Id,
    this.driverId,
    this.origin,
    this.destination,
    this.stops,
    this.tripType,
    this.recurringTrip,
    this.date,
    this.time,
    this.returnTrip,
    this.arrivalDate,
    this.arrivalTime,
    this.totalSeatAvailable,
    this.seatAvailable,
    this.preferences,
    this.isStarted,
    this.isCompleted,
    this.isCancelled,
    this.description,
    this.endDateTime,
    this.createdAt,
    this.updatedAt,
  });
  PrevRidesDataDataRecurringInstances.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    driverId = json['driverId']?.toString();
    origin = (json['origin'] != null) ? PrevRidesDataDataRecurringInstancesOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? PrevRidesDataDataRecurringInstancesDestination.fromJson(json['destination']) : null;
  if (json['stops'] != null) {
  final v = json['stops'];
  final arr0 = <PrevRidesDataDataRecurringInstancesStops>[];
  v.forEach((v) {
  arr0.add(PrevRidesDataDataRecurringInstancesStops.fromJson(v));
  });
    stops = arr0;
    }
    tripType = json['tripType']?.toString();
    recurringTrip = (json['recurringTrip'] != null) ? PrevRidesDataDataRecurringInstancesRecurringTrip.fromJson(json['recurringTrip']) : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    returnTrip = (json['returnTrip'] != null) ? PrevRidesDataDataRecurringInstancesReturnTrip.fromJson(json['returnTrip']) : null;
    arrivalDate = json['arrivalDate']?.toString();
    arrivalTime = json['arrivalTime']?.toString();
    totalSeatAvailable = json['totalSeatAvailable']?.toInt();
    seatAvailable = json['seatAvailable']?.toInt();
    preferences = (json['preferences'] != null) ? PrevRidesDataDataRecurringInstancesPreferences.fromJson(json['preferences']) : null;
    isStarted = json['isStarted'];
    isCompleted = json['isCompleted'];
    isCancelled = json['isCancelled'];
    description = json['description']?.toString();
    endDateTime = json['endDateTime']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['driverId'] = driverId;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (stops != null) {
      final v = stops;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['stops'] = arr0;
    }
    data['tripType'] = tripType;
    if (recurringTrip != null) {
      data['recurringTrip'] = recurringTrip!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    if (returnTrip != null) {
      data['returnTrip'] = returnTrip!.toJson();
    }
    data['arrivalDate'] = arrivalDate;
    data['arrivalTime'] = arrivalTime;
    data['totalSeatAvailable'] = totalSeatAvailable;
    data['seatAvailable'] = seatAvailable;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['isStarted'] = isStarted;
    data['isCompleted'] = isCompleted;
    data['isCancelled'] = isCancelled;
    data['description'] = description;
    data['endDateTime'] = endDateTime;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class PrevRidesDataDataPreferencesOther {
/*
{
  "AppreciatesConversation": false,
  "EnjoysMusic": false,
  "SmokeFree": false,
  "PetFriendly": false,
  "WinterTires": false,
  "CoolingOrHeating": false,
  "BabySeat": false,
  "HeatedSeats": false
} 
*/

  bool? AppreciatesConversation;
  bool? EnjoysMusic;
  bool? SmokeFree;
  bool? PetFriendly;
  bool? WinterTires;
  bool? CoolingOrHeating;
  bool? BabySeat;
  bool? HeatedSeats;

  PrevRidesDataDataPreferencesOther({
    this.AppreciatesConversation,
    this.EnjoysMusic,
    this.SmokeFree,
    this.PetFriendly,
    this.WinterTires,
    this.CoolingOrHeating,
    this.BabySeat,
    this.HeatedSeats,
  });
  PrevRidesDataDataPreferencesOther.fromJson(Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
    EnjoysMusic = json['EnjoysMusic'];
    SmokeFree = json['SmokeFree'];
    PetFriendly = json['PetFriendly'];
    WinterTires = json['WinterTires'];
    CoolingOrHeating = json['CoolingOrHeating'];
    BabySeat = json['BabySeat'];
    HeatedSeats = json['HeatedSeats'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    data['EnjoysMusic'] = EnjoysMusic;
    data['SmokeFree'] = SmokeFree;
    data['PetFriendly'] = PetFriendly;
    data['WinterTires'] = WinterTires;
    data['CoolingOrHeating'] = CoolingOrHeating;
    data['BabySeat'] = BabySeat;
    data['HeatedSeats'] = HeatedSeats;
    return data;
  }
}

class PrevRidesDataDataPreferences {
/*
{
  "luggageType": "No",
  "other": {
    "AppreciatesConversation": false,
    "EnjoysMusic": false,
    "SmokeFree": false,
    "PetFriendly": false,
    "WinterTires": false,
    "CoolingOrHeating": false,
    "BabySeat": false,
    "HeatedSeats": false
  }
} 
*/

  String? luggageType;
  PrevRidesDataDataPreferencesOther? other;

  PrevRidesDataDataPreferences({
    this.luggageType,
    this.other,
  });
  PrevRidesDataDataPreferences.fromJson(Map<String, dynamic> json) {
    luggageType = json['luggageType']?.toString();
    other = (json['other'] != null) ? PrevRidesDataDataPreferencesOther.fromJson(json['other']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['luggageType'] = luggageType;
    if (other != null) {
      data['other'] = other!.toJson();
    }
    return data;
  }
}

class PrevRidesDataDataReturnTrip {
/*
{
  "isReturnTrip": false,
  "returnDate": null,
  "returnTime": ""
} 
*/

  bool? isReturnTrip;
  String? returnDate;
  String? returnTime;

  PrevRidesDataDataReturnTrip({
    this.isReturnTrip,
    this.returnDate,
    this.returnTime,
  });
  PrevRidesDataDataReturnTrip.fromJson(Map<String, dynamic> json) {
    isReturnTrip = json['isReturnTrip'];
    returnDate = json['returnDate']?.toString();
    returnTime = json['returnTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isReturnTrip'] = isReturnTrip;
    data['returnDate'] = returnDate;
    data['returnTime'] = returnTime;
    return data;
  }
}

class PrevRidesDataDataRecurringTrip {
/*
{
  "recurringTripDays": [
    1
  ],
  "recurringTripIds": [
    ""
  ],
  "isRecurringTripEnabled": false
} 
*/

  List<int?>? recurringTripDays;
  List<String?>? recurringTripIds;
  bool? isRecurringTripEnabled;

  PrevRidesDataDataRecurringTrip({
    this.recurringTripDays,
    this.recurringTripIds,
    this.isRecurringTripEnabled,
  });
  PrevRidesDataDataRecurringTrip.fromJson(Map<String, dynamic> json) {
  if (json['recurringTripDays'] != null) {
  final v = json['recurringTripDays'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    recurringTripDays = arr0;
    }
  if (json['recurringTripIds'] != null) {
  final v = json['recurringTripIds'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    recurringTripIds = arr0;
    }
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recurringTripDays != null) {
      final v = recurringTripDays;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripDays'] = arr0;
    }
    if (recurringTripIds != null) {
      final v = recurringTripIds;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripIds'] = arr0;
    }
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    return data;
  }
}

class PrevRidesDataDataStops {
/*
{
  "time": null,
  "name": "",
  "type": "Point",
  "coordinates": [
    -78.9400809
  ],
  "originToStopFair": "",
  "stopToStopFair": "",
  "stopTodestinationFair": "",
  "_id": "67ffa91c87e55dfc41338435"
} 
*/

  String? time;
  String? name;
  String? type;
  List<double?>? coordinates;
  String? originToStopFair;
  String? stopToStopFair;
  String? stopTodestinationFair;
  String? Id;

  PrevRidesDataDataStops({
    this.time,
    this.name,
    this.type,
    this.coordinates,
    this.originToStopFair,
    this.stopToStopFair,
    this.stopTodestinationFair,
    this.Id,
  });
  PrevRidesDataDataStops.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originToStopFair = json['originToStopFair']?.toString();
    stopToStopFair = json['stopToStopFair']?.toString();
    stopTodestinationFair = json['stopTodestinationFair']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originToStopFair'] = originToStopFair;
    data['stopToStopFair'] = stopToStopFair;
    data['stopTodestinationFair'] = stopTodestinationFair;
    data['_id'] = Id;
    return data;
  }
}

class PrevRidesDataDataDestination {
/*
{
  "name": "Whitby, ON, Canada",
  "type": "Point",
  "coordinates": [
    -78.9400809
  ]
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;

  PrevRidesDataDataDestination({
    this.name,
    this.type,
    this.coordinates,
  });
  PrevRidesDataDataDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class PrevRidesDataDataOrigin {
/*
{
  "name": "Oshawa, ON, Canada",
  "type": "Point",
  "coordinates": [
    -78.8635999
  ],
  "originDestinationFair": "5",
  "time": ""
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;
  String? originDestinationFair;
  String? time;

  PrevRidesDataDataOrigin({
    this.name,
    this.type,
    this.coordinates,
    this.originDestinationFair,
    this.time,
  });
  PrevRidesDataDataOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originDestinationFair = json['originDestinationFair']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originDestinationFair'] = originDestinationFair;
    data['time'] = time;
    return data;
  }
}

class PrevRidesDataData {
/*
{
  "_id": "67ffa91c87e55dfc41338434",
  "driverId": "67654c4898c6452c56f9a007",
  "origin": {
    "name": "Oshawa, ON, Canada",
    "type": "Point",
    "coordinates": [
      -78.8635999
    ],
    "originDestinationFair": "5",
    "time": ""
  },
  "destination": {
    "name": "Whitby, ON, Canada",
    "type": "Point",
    "coordinates": [
      -78.9400809
    ]
  },
  "stops": [
    {
      "time": null,
      "name": "",
      "type": "Point",
      "coordinates": [
        -78.9400809
      ],
      "originToStopFair": "",
      "stopToStopFair": "",
      "stopTodestinationFair": "",
      "_id": "67ffa91c87e55dfc41338435"
    }
  ],
  "tripType": "oneTime",
  "recurringTrip": {
    "recurringTripDays": [
      1
    ],
    "recurringTripIds": [
      ""
    ],
    "isRecurringTripEnabled": false
  },
  "date": "2025-04-16T00:00:00.000Z",
  "time": "2025-04-16T13:30:00.000Z",
  "returnTrip": {
    "isReturnTrip": false,
    "returnDate": null,
    "returnTime": ""
  },
  "arrivalDate": null,
  "arrivalTime": null,
  "totalSeatAvailable": 1,
  "seatAvailable": 1,
  "preferences": {
    "luggageType": "No",
    "other": {
      "AppreciatesConversation": false,
      "EnjoysMusic": false,
      "SmokeFree": false,
      "PetFriendly": false,
      "WinterTires": false,
      "CoolingOrHeating": false,
      "BabySeat": false,
      "HeatedSeats": false
    }
  },
  "isStarted": false,
  "isCompleted": false,
  "isCancelled": false,
  "description": null,
  "endDateTime": "2025-04-16T12:57:00.242Z",
  "createdAt": "2025-04-16T12:57:00.256Z",
  "updatedAt": "2025-04-16T12:57:00.256Z",
  "isRecurring": false,
  "instanceCount": 1,
  "recurringInstances": [
    {
      "_id": "67fca5fd8a71186dc7b8df29",
      "driverId": "67654c4898c6452c56f9a007",
      "origin": {
        "name": "Oshawa, ON, Canada",
        "type": "Point",
        "coordinates": [
          -78.8635999
        ],
        "originDestinationFair": "5",
        "time": ""
      },
      "destination": {
        "name": "Whitby, ON, Canada",
        "type": "Point",
        "coordinates": [
          -78.9400809
        ]
      },
      "stops": [
        {
          "time": null,
          "name": "",
          "type": "Point",
          "coordinates": [
            0
          ],
          "originToStopFair": "",
          "stopToStopFair": "",
          "stopTodestinationFair": "",
          "_id": "67fca5fd8a71186dc7b8df2a"
        }
      ],
      "tripType": "oneTime",
      "recurringTrip": {
        "recurringTripDays": [
          1
        ],
        "recurringTripIds": [
          ""
        ],
        "isRecurringTripEnabled": false
      },
      "date": "2025-04-19T00:00:00.000Z",
      "time": "2025-04-19T10:50:00.000Z",
      "returnTrip": {
        "isReturnTrip": false,
        "returnDate": null,
        "returnTime": null
      },
      "arrivalDate": null,
      "arrivalTime": null,
      "totalSeatAvailable": 3,
      "seatAvailable": 3,
      "preferences": {
        "luggageType": "S",
        "other": {
          "AppreciatesConversation": true,
          "EnjoysMusic": false,
          "SmokeFree": false,
          "PetFriendly": false,
          "WinterTires": false,
          "CoolingOrHeating": false,
          "BabySeat": false,
          "HeatedSeats": false
        }
      },
      "isStarted": false,
      "isCompleted": false,
      "isCancelled": false,
      "description": null,
      "endDateTime": "2025-04-14T06:06:53.744Z",
      "createdAt": "2025-04-14T06:06:53.790Z",
      "updatedAt": "2025-04-14T06:06:53.790Z"
    }
  ],
  "nextRideDate": "2025-04-19T00:00:00.000Z"
} 
*/

  String? Id;
  String? driverId;
  PrevRidesDataDataOrigin? origin;
  PrevRidesDataDataDestination? destination;
  List<PrevRidesDataDataStops?>? stops;
  String? tripType;
  PrevRidesDataDataRecurringTrip? recurringTrip;
  String? date;
  String? time;
  PrevRidesDataDataReturnTrip? returnTrip;
  String? arrivalDate;
  String? arrivalTime;
  int? totalSeatAvailable;
  int? seatAvailable;
  PrevRidesDataDataPreferences? preferences;
  bool? isStarted;
  bool? isCompleted;
  bool? isCancelled;
  String? description;
  String? endDateTime;
  String? createdAt;
  String? updatedAt;
  bool? isRecurring;
  int? instanceCount;
  List<PrevRidesDataDataRecurringInstances?>? recurringInstances;
  String? nextRideDate;

  PrevRidesDataData({
    this.Id,
    this.driverId,
    this.origin,
    this.destination,
    this.stops,
    this.tripType,
    this.recurringTrip,
    this.date,
    this.time,
    this.returnTrip,
    this.arrivalDate,
    this.arrivalTime,
    this.totalSeatAvailable,
    this.seatAvailable,
    this.preferences,
    this.isStarted,
    this.isCompleted,
    this.isCancelled,
    this.description,
    this.endDateTime,
    this.createdAt,
    this.updatedAt,
    this.isRecurring,
    this.instanceCount,
    this.recurringInstances,
    this.nextRideDate,
  });
  PrevRidesDataData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    driverId = json['driverId']?.toString();
    origin = (json['origin'] != null) ? PrevRidesDataDataOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? PrevRidesDataDataDestination.fromJson(json['destination']) : null;
  if (json['stops'] != null) {
  final v = json['stops'];
  final arr0 = <PrevRidesDataDataStops>[];
  v.forEach((v) {
  arr0.add(PrevRidesDataDataStops.fromJson(v));
  });
    stops = arr0;
    }
    tripType = json['tripType']?.toString();
    recurringTrip = (json['recurringTrip'] != null) ? PrevRidesDataDataRecurringTrip.fromJson(json['recurringTrip']) : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    returnTrip = (json['returnTrip'] != null) ? PrevRidesDataDataReturnTrip.fromJson(json['returnTrip']) : null;
    arrivalDate = json['arrivalDate']?.toString();
    arrivalTime = json['arrivalTime']?.toString();
    totalSeatAvailable = json['totalSeatAvailable']?.toInt();
    seatAvailable = json['seatAvailable']?.toInt();
    preferences = (json['preferences'] != null) ? PrevRidesDataDataPreferences.fromJson(json['preferences']) : null;
    isStarted = json['isStarted'];
    isCompleted = json['isCompleted'];
    isCancelled = json['isCancelled'];
    description = json['description']?.toString();
    endDateTime = json['endDateTime']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    isRecurring = json['isRecurring'];
    instanceCount = json['instanceCount']?.toInt();
  if (json['recurringInstances'] != null) {
  final v = json['recurringInstances'];
  final arr0 = <PrevRidesDataDataRecurringInstances>[];
  v.forEach((v) {
  arr0.add(PrevRidesDataDataRecurringInstances.fromJson(v));
  });
    recurringInstances = arr0;
    }
    nextRideDate = json['nextRideDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['driverId'] = driverId;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (stops != null) {
      final v = stops;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['stops'] = arr0;
    }
    data['tripType'] = tripType;
    if (recurringTrip != null) {
      data['recurringTrip'] = recurringTrip!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    if (returnTrip != null) {
      data['returnTrip'] = returnTrip!.toJson();
    }
    data['arrivalDate'] = arrivalDate;
    data['arrivalTime'] = arrivalTime;
    data['totalSeatAvailable'] = totalSeatAvailable;
    data['seatAvailable'] = seatAvailable;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['isStarted'] = isStarted;
    data['isCompleted'] = isCompleted;
    data['isCancelled'] = isCancelled;
    data['description'] = description;
    data['endDateTime'] = endDateTime;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['isRecurring'] = isRecurring;
    data['instanceCount'] = instanceCount;
    if (recurringInstances != null) {
      final v = recurringInstances;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['recurringInstances'] = arr0;
    }
    data['nextRideDate'] = nextRideDate;
    return data;
  }
}

class PrevRidesData {
/*
{
  "status": true,
  "message": "Recent rides fetched successfully",
  "data": [
    {
      "_id": "67ffa91c87e55dfc41338434",
      "driverId": "67654c4898c6452c56f9a007",
      "origin": {
        "name": "Oshawa, ON, Canada",
        "type": "Point",
        "coordinates": [
          -78.8635999
        ],
        "originDestinationFair": "5",
        "time": ""
      },
      "destination": {
        "name": "Whitby, ON, Canada",
        "type": "Point",
        "coordinates": [
          -78.9400809
        ]
      },
      "stops": [
        {
          "time": null,
          "name": "",
          "type": "Point",
          "coordinates": [
            -78.9400809
          ],
          "originToStopFair": "",
          "stopToStopFair": "",
          "stopTodestinationFair": "",
          "_id": "67ffa91c87e55dfc41338435"
        }
      ],
      "tripType": "oneTime",
      "recurringTrip": {
        "recurringTripDays": [
          1
        ],
        "recurringTripIds": [
          ""
        ],
        "isRecurringTripEnabled": false
      },
      "date": "2025-04-16T00:00:00.000Z",
      "time": "2025-04-16T13:30:00.000Z",
      "returnTrip": {
        "isReturnTrip": false,
        "returnDate": null,
        "returnTime": ""
      },
      "arrivalDate": null,
      "arrivalTime": null,
      "totalSeatAvailable": 1,
      "seatAvailable": 1,
      "preferences": {
        "luggageType": "No",
        "other": {
          "AppreciatesConversation": false,
          "EnjoysMusic": false,
          "SmokeFree": false,
          "PetFriendly": false,
          "WinterTires": false,
          "CoolingOrHeating": false,
          "BabySeat": false,
          "HeatedSeats": false
        }
      },
      "isStarted": false,
      "isCompleted": false,
      "isCancelled": false,
      "description": null,
      "endDateTime": "2025-04-16T12:57:00.242Z",
      "createdAt": "2025-04-16T12:57:00.256Z",
      "updatedAt": "2025-04-16T12:57:00.256Z",
      "isRecurring": false,
      "instanceCount": 1,
      "recurringInstances": [
        {
          "_id": "67fca5fd8a71186dc7b8df29",
          "driverId": "67654c4898c6452c56f9a007",
          "origin": {
            "name": "Oshawa, ON, Canada",
            "type": "Point",
            "coordinates": [
              -78.8635999
            ],
            "originDestinationFair": "5",
            "time": ""
          },
          "destination": {
            "name": "Whitby, ON, Canada",
            "type": "Point",
            "coordinates": [
              -78.9400809
            ]
          },
          "stops": [
            {
              "time": null,
              "name": "",
              "type": "Point",
              "coordinates": [
                0
              ],
              "originToStopFair": "",
              "stopToStopFair": "",
              "stopTodestinationFair": "",
              "_id": "67fca5fd8a71186dc7b8df2a"
            }
          ],
          "tripType": "oneTime",
          "recurringTrip": {
            "recurringTripDays": [
              1
            ],
            "recurringTripIds": [
              ""
            ],
            "isRecurringTripEnabled": false
          },
          "date": "2025-04-19T00:00:00.000Z",
          "time": "2025-04-19T10:50:00.000Z",
          "returnTrip": {
            "isReturnTrip": false,
            "returnDate": null,
            "returnTime": null
          },
          "arrivalDate": null,
          "arrivalTime": null,
          "totalSeatAvailable": 3,
          "seatAvailable": 3,
          "preferences": {
            "luggageType": "S",
            "other": {
              "AppreciatesConversation": true,
              "EnjoysMusic": false,
              "SmokeFree": false,
              "PetFriendly": false,
              "WinterTires": false,
              "CoolingOrHeating": false,
              "BabySeat": false,
              "HeatedSeats": false
            }
          },
          "isStarted": false,
          "isCompleted": false,
          "isCancelled": false,
          "description": null,
          "endDateTime": "2025-04-14T06:06:53.744Z",
          "createdAt": "2025-04-14T06:06:53.790Z",
          "updatedAt": "2025-04-14T06:06:53.790Z"
        }
      ],
      "nextRideDate": "2025-04-19T00:00:00.000Z"
    }
  ]
} 
*/

  bool? status;
  String? message;
  List<PrevRidesDataData?>? data;

  PrevRidesData({
    this.status,
    this.message,
    this.data,
  });
  PrevRidesData.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <PrevRidesDataData>[];
  v.forEach((v) {
  arr0.add(PrevRidesDataData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}

class PrevRides {
/*
{
  "status": "success",
  "data": {
    "status": true,
    "message": "Recent rides fetched successfully",
    "data": [
      {
        "_id": "67ffa91c87e55dfc41338434",
        "driverId": "67654c4898c6452c56f9a007",
        "origin": {
          "name": "Oshawa, ON, Canada",
          "type": "Point",
          "coordinates": [
            -78.8635999
          ],
          "originDestinationFair": "5",
          "time": ""
        },
        "destination": {
          "name": "Whitby, ON, Canada",
          "type": "Point",
          "coordinates": [
            -78.9400809
          ]
        },
        "stops": [
          {
            "time": null,
            "name": "",
            "type": "Point",
            "coordinates": [
              -78.9400809
            ],
            "originToStopFair": "",
            "stopToStopFair": "",
            "stopTodestinationFair": "",
            "_id": "67ffa91c87e55dfc41338435"
          }
        ],
        "tripType": "oneTime",
        "recurringTrip": {
          "recurringTripDays": [
            1
          ],
          "recurringTripIds": [
            ""
          ],
          "isRecurringTripEnabled": false
        },
        "date": "2025-04-16T00:00:00.000Z",
        "time": "2025-04-16T13:30:00.000Z",
        "returnTrip": {
          "isReturnTrip": false,
          "returnDate": null,
          "returnTime": ""
        },
        "arrivalDate": null,
        "arrivalTime": null,
        "totalSeatAvailable": 1,
        "seatAvailable": 1,
        "preferences": {
          "luggageType": "No",
          "other": {
            "AppreciatesConversation": false,
            "EnjoysMusic": false,
            "SmokeFree": false,
            "PetFriendly": false,
            "WinterTires": false,
            "CoolingOrHeating": false,
            "BabySeat": false,
            "HeatedSeats": false
          }
        },
        "isStarted": false,
        "isCompleted": false,
        "isCancelled": false,
        "description": null,
        "endDateTime": "2025-04-16T12:57:00.242Z",
        "createdAt": "2025-04-16T12:57:00.256Z",
        "updatedAt": "2025-04-16T12:57:00.256Z",
        "isRecurring": false,
        "instanceCount": 1,
        "recurringInstances": [
          {
            "_id": "67fca5fd8a71186dc7b8df29",
            "driverId": "67654c4898c6452c56f9a007",
            "origin": {
              "name": "Oshawa, ON, Canada",
              "type": "Point",
              "coordinates": [
                -78.8635999
              ],
              "originDestinationFair": "5",
              "time": ""
            },
            "destination": {
              "name": "Whitby, ON, Canada",
              "type": "Point",
              "coordinates": [
                -78.9400809
              ]
            },
            "stops": [
              {
                "time": null,
                "name": "",
                "type": "Point",
                "coordinates": [
                  0
                ],
                "originToStopFair": "",
                "stopToStopFair": "",
                "stopTodestinationFair": "",
                "_id": "67fca5fd8a71186dc7b8df2a"
              }
            ],
            "tripType": "oneTime",
            "recurringTrip": {
              "recurringTripDays": [
                1
              ],
              "recurringTripIds": [
                ""
              ],
              "isRecurringTripEnabled": false
            },
            "date": "2025-04-19T00:00:00.000Z",
            "time": "2025-04-19T10:50:00.000Z",
            "returnTrip": {
              "isReturnTrip": false,
              "returnDate": null,
              "returnTime": null
            },
            "arrivalDate": null,
            "arrivalTime": null,
            "totalSeatAvailable": 3,
            "seatAvailable": 3,
            "preferences": {
              "luggageType": "S",
              "other": {
                "AppreciatesConversation": true,
                "EnjoysMusic": false,
                "SmokeFree": false,
                "PetFriendly": false,
                "WinterTires": false,
                "CoolingOrHeating": false,
                "BabySeat": false,
                "HeatedSeats": false
              }
            },
            "isStarted": false,
            "isCompleted": false,
            "isCancelled": false,
            "description": null,
            "endDateTime": "2025-04-14T06:06:53.744Z",
            "createdAt": "2025-04-14T06:06:53.790Z",
            "updatedAt": "2025-04-14T06:06:53.790Z"
          }
        ],
        "nextRideDate": "2025-04-19T00:00:00.000Z"
      }
    ]
  }
} 
*/

  String? status;
  PrevRidesData? data;

  PrevRides({
    this.status,
    this.data,
  });
  PrevRides.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    data = (json['data'] != null) ? PrevRidesData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
