name: green_pool
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  new_version_plus: ^0.0.11
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  firebase_auth: ^4.20.0
  flutter_native_timezone_updated_gradle: ^2.0.3
  stacked_firebase_auth: ^2.20.0
  firebase_core: ^2.32.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  pinput: ^4.0.0
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  country_code_picker: ^3.0.0
  geolocator: ^12.0.0
  uuid: ^4.4.0
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  path: ^1.9.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.1
  firebase_messaging: ^14.9.4
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  firebase_database: ^10.5.7
  confetti: ^0.7.0
  share_plus: ^9.0.0
  http_parser: ^4.0.2
  webview_flutter: ^4.8.0
  flutter_google_maps_webservices: ^1.1.1
  icons_launcher: ^2.1.7
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  flutter_facebook_auth: ^6.2.0
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/images/icons/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/messages/
    - assets/images/createacc/
    - assets/images/guidelines/
    - assets/images/setupprofile/
    - assets/images/bottomnavbar/
    - assets/images/myrides/
    - assets/images/navigation/
    - assets/images/wallet/
    - assets/svg/