name: green_pool
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.4.0
  google_fonts: ^6.1.0
  new_version_plus: ^0.0.11
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  firebase_auth: ^4.15.0
  flutter_facebook_auth: ^6.0.3
  stacked_firebase_auth: ^2.19.6
  firebase_core: ^2.24.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  pinput: ^3.0.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  country_code_picker: ^3.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/messages/
    - assets/images/createacc/
    - assets/images/guidelines/
    - assets/images/setupprofile/
    - assets/images/bottomnavbar/
    - assets/images/myrides/
