name: green_pool
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.4.2+1
  google_fonts: ^6.2.1
  new_version_plus: ^0.0.11
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  firebase_auth: ^4.18.0
  flutter_facebook_auth: ^6.1.1
  stacked_firebase_auth: ^2.20.0
  firebase_core: ^2.28.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  pinput: ^4.0.0
  google_maps_flutter: ^2.6.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.2.0
  country_code_picker: ^3.0.0
  geolocator: ^11.0.0
  uuid: ^4.3.3
  google_places_flutter: ^2.0.8
  http: ^1.2.0
  path: ^1.9.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  firebase_messaging: ^14.8.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.0.0
  firebase_database: ^10.5.1
  confetti: ^0.7.0
  share_plus: ^9.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/messages/
    - assets/images/createacc/
    - assets/images/guidelines/
    - assets/images/setupprofile/
    - assets/images/bottomnavbar/
    - assets/images/myrides/
    - assets/images/navigation/
    - assets/images/wallet/
