///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddVehicleDataVehicleDetailsVehiclePic {
/*
{
  "key": "mypic",
  "url": "https://www.pexels.com/photo/composition-of-august-letters-on-table-4926898/"
} 
*/

  String? key;
  String? url;

  AddVehicleDataVehicleDetailsVehiclePic({
    this.key,
    this.url,
  });
  AddVehicleDataVehicleDetailsVehiclePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class AddVehicleDataVehicleDetails {
/*
{
  "vehiclePic": {
    "key": "mypic",
    "url": "https://www.pexels.com/photo/composition-of-august-letters-on-table-4926898/"
  },
  "model": "ABCDmd",
  "type": "abcd",
  "color": "red",
  "year": 2020,
  "licencePlate": "A109DC"
} 
*/

  AddVehicleDataVehicleDetailsVehiclePic? vehiclePic;
  String? model;
  String? type;
  String? color;
  int? year;
  String? licencePlate;

  AddVehicleDataVehicleDetails({
    this.vehiclePic,
    this.model,
    this.type,
    this.color,
    this.year,
    this.licencePlate,
  });
  AddVehicleDataVehicleDetails.fromJson(Map<String, dynamic> json) {
    vehiclePic = (json['vehiclePic'] != null)
        ? AddVehicleDataVehicleDetailsVehiclePic.fromJson(json['vehiclePic'])
        : null;
    model = json['model']?.toString();
    type = json['type']?.toString();
    color = json['color']?.toString();
    year = json['year']?.toInt();
    licencePlate = json['licencePlate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (vehiclePic != null) {
      data['vehiclePic'] = vehiclePic!.toJson();
    }
    data['model'] = model;
    data['type'] = type;
    data['color'] = color;
    data['year'] = year;
    data['licencePlate'] = licencePlate;
    return data;
  }
}

class AddVehicleData {
/*
{
  "_id": "658d73de07d59f24b575f8e0",
  "vehicleDetails": {
    "vehiclePic": {
      "key": "mypic",
      "url": "https://www.pexels.com/photo/composition-of-august-letters-on-table-4926898/"
    },
    "model": "ABCDmd",
    "type": "abcd",
    "color": "red",
    "year": 2020,
    "licencePlate": "A109DC"
  }
} 
*/

  String? Id;
  AddVehicleDataVehicleDetails? vehicleDetails;

  AddVehicleData({
    this.Id,
    this.vehicleDetails,
  });
  AddVehicleData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    vehicleDetails = (json['vehicleDetails'] != null)
        ? AddVehicleDataVehicleDetails.fromJson(json['vehicleDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    if (vehicleDetails != null) {
      data['vehicleDetails'] = vehicleDetails!.toJson();
    }
    return data;
  }
}
