///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetailsVehiclePic {
/*
{
  "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
  "_id": "6639b8a358249d84ebc50640"
} 
*/

  String? key;
  String? url;
  String? Id;

  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetailsVehiclePic({
    this.key,
    this.url,
    this.Id,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetailsVehiclePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetails {
/*
{
  "_id": "6639b8a358249d84ebc5063f",
  "driverId": "6639b78f58249d84ebc5062f",
  "vehiclePic": {
    "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
    "_id": "6639b8a358249d84ebc50640"
  },
  "model": "iuModel",
  "type": "Sedan",
  "color": "Silver",
  "year": 2000,
  "licencePlate": "CA2000",
  "createdAt": "2024-05-07T05:14:11.059Z",
  "updatedAt": "2024-05-07T05:14:11.059Z"
} 
*/

  String? Id;
  String? driverId;
  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetailsVehiclePic? vehiclePic;
  String? model;
  String? type;
  String? color;
  int? year;
  String? licencePlate;
  String? createdAt;
  String? updatedAt;

  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetails({
    this.Id,
    this.driverId,
    this.vehiclePic,
    this.model,
    this.type,
    this.color,
    this.year,
    this.licencePlate,
    this.createdAt,
    this.updatedAt,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    driverId = json['driverId']?.toString();
    vehiclePic = (json['vehiclePic'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetailsVehiclePic.fromJson(json['vehiclePic']) : null;
    model = json['model']?.toString();
    type = json['type']?.toString();
    color = json['color']?.toString();
    year = json['year']?.toInt();
    licencePlate = json['licencePlate']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['driverId'] = driverId;
    if (vehiclePic != null) {
      data['vehiclePic'] = vehiclePic!.toJson();
    }
    data['model'] = model;
    data['type'] = type;
    data['color'] = color;
    data['year'] = year;
    data['licencePlate'] = licencePlate;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDriverDetailsNotificationPreferences {
/*
{
  "trip": true,
  "alerts": true,
  "payments": true,
  "transactions": true,
  "offers": true
} 
*/

  bool? trip;
  bool? alerts;
  bool? payments;
  bool? transactions;
  bool? offers;

  BookingDetailModelDataDriverBookingDetailsDriverDetailsNotificationPreferences({
    this.trip,
    this.alerts,
    this.payments,
    this.transactions,
    this.offers,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetailsNotificationPreferences.fromJson(Map<String, dynamic> json) {
    trip = json['trip'];
    alerts = json['alerts'];
    payments = json['payments'];
    transactions = json['transactions'];
    offers = json['offers'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    data['alerts'] = alerts;
    data['payments'] = payments;
    data['transactions'] = transactions;
    data['offers'] = offers;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDriverDetailsIdPic {
/*
{
  "key": "idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
  "_id": "6639b83358249d84ebc50639"
} 
*/

  String? key;
  String? url;
  String? Id;

  BookingDetailModelDataDriverBookingDetailsDriverDetailsIdPic({
    this.key,
    this.url,
    this.Id,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetailsIdPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDriverDetailsProfilePic {
/*
{
  "key": "usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
  "_id": "6639b83358249d84ebc50638"
} 
*/

  String? key;
  String? url;
  String? Id;

  BookingDetailModelDataDriverBookingDetailsDriverDetailsProfilePic({
    this.key,
    this.url,
    this.Id,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetailsProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDriverDetails {
/*
{
  "_id": "6639b78f58249d84ebc5062f",
  "isRegister": true,
  "pinkMode": false,
  "fullName": "Zen",
  "phone": "+11234512345",
  "email": "zen@test.com",
  "city": "Brampton",
  "profilePic": {
    "key": "usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
    "_id": "6639b83358249d84ebc50638"
  },
  "idPic": {
    "key": "idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
    "_id": "6639b83358249d84ebc50639"
  },
  "dob": "2006-05-12",
  "gender": "Male",
  "isDriver": true,
  "referralCode": "N5213I5793",
  "profileStatus": true,
  "vehicleStatus": true,
  "status": "active",
  "wallet": 0,
  "rating": 0,
  "totalRides": 0,
  "isRecurringTripEnabled": false,
  "notificationPreferences": {
    "trip": true,
    "alerts": true,
    "payments": true,
    "transactions": true,
    "offers": true
  },
  "firebaseUid": "n9XvgstaJCShxg2V5AmREneUYOE2",
  "firebaseSignInProvider": "phone",
  "createdAt": "2024-05-07T05:09:35.528Z",
  "updatedAt": "2024-05-08T09:23:23.028Z",
  "role": "user",
  "vechileDetails": {
    "_id": "6639b8a358249d84ebc5063f",
    "driverId": "6639b78f58249d84ebc5062f",
    "vehiclePic": {
      "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
      "_id": "6639b8a358249d84ebc50640"
    },
    "model": "iuModel",
    "type": "Sedan",
    "color": "Silver",
    "year": 2000,
    "licencePlate": "CA2000",
    "createdAt": "2024-05-07T05:14:11.059Z",
    "updatedAt": "2024-05-07T05:14:11.059Z"
  }
} 
*/

  String? Id;
  bool? isRegister;
  bool? pinkMode;
  String? fullName;
  String? phone;
  String? email;
  String? city;
  BookingDetailModelDataDriverBookingDetailsDriverDetailsProfilePic? profilePic;
  BookingDetailModelDataDriverBookingDetailsDriverDetailsIdPic? idPic;
  String? dob;
  String? gender;
  bool? isDriver;
  String? referralCode;
  bool? profileStatus;
  bool? vehicleStatus;
  String? status;
  int? wallet;
  int? rating;
  int? totalRides;
  bool? isRecurringTripEnabled;
  BookingDetailModelDataDriverBookingDetailsDriverDetailsNotificationPreferences? notificationPreferences;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? createdAt;
  String? updatedAt;
  String? role;
  BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetails? vechileDetails;

  BookingDetailModelDataDriverBookingDetailsDriverDetails({
    this.Id,
    this.isRegister,
    this.pinkMode,
    this.fullName,
    this.phone,
    this.email,
    this.city,
    this.profilePic,
    this.idPic,
    this.dob,
    this.gender,
    this.isDriver,
    this.referralCode,
    this.profileStatus,
    this.vehicleStatus,
    this.status,
    this.wallet,
    this.rating,
    this.totalRides,
    this.isRecurringTripEnabled,
    this.notificationPreferences,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.createdAt,
    this.updatedAt,
    this.role,
    this.vechileDetails,
  });
  BookingDetailModelDataDriverBookingDetailsDriverDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    isRegister = json['isRegister'];
    pinkMode = json['pinkMode'];
    fullName = json['fullName']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    city = json['city']?.toString();
    profilePic = (json['profilePic'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetailsProfilePic.fromJson(json['profilePic']) : null;
    idPic = (json['idPic'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetailsIdPic.fromJson(json['idPic']) : null;
    dob = json['dob']?.toString();
    gender = json['gender']?.toString();
    isDriver = json['isDriver'];
    referralCode = json['referralCode']?.toString();
    profileStatus = json['profileStatus'];
    vehicleStatus = json['vehicleStatus'];
    status = json['status']?.toString();
    wallet = json['wallet']?.toInt();
    rating = json['rating']?.toInt();
    totalRides = json['totalRides']?.toInt();
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
    notificationPreferences = (json['notificationPreferences'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetailsNotificationPreferences.fromJson(json['notificationPreferences']) : null;
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    role = json['role']?.toString();
    vechileDetails = (json['vechileDetails'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetailsVechileDetails.fromJson(json['vechileDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['isRegister'] = isRegister;
    data['pinkMode'] = pinkMode;
    data['fullName'] = fullName;
    data['phone'] = phone;
    data['email'] = email;
    data['city'] = city;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    if (idPic != null) {
      data['idPic'] = idPic!.toJson();
    }
    data['dob'] = dob;
    data['gender'] = gender;
    data['isDriver'] = isDriver;
    data['referralCode'] = referralCode;
    data['profileStatus'] = profileStatus;
    data['vehicleStatus'] = vehicleStatus;
    data['status'] = status;
    data['wallet'] = wallet;
    data['rating'] = rating;
    data['totalRides'] = totalRides;
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    if (notificationPreferences != null) {
      data['notificationPreferences'] = notificationPreferences!.toJson();
    }
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['role'] = role;
    if (vechileDetails != null) {
      data['vechileDetails'] = vechileDetails!.toJson();
    }
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferencesOther {
/*
{
  "AppreciatesConversation": false,
  "EnjoysMusic": false,
  "SmokeFree": false,
  "PetFriendly": false,
  "WinterTires": false,
  "CoolingOrHeating": false,
  "BabySeat": false,
  "HeatedSeats": false
} 
*/

  bool? AppreciatesConversation;
  bool? EnjoysMusic;
  bool? SmokeFree;
  bool? PetFriendly;
  bool? WinterTires;
  bool? CoolingOrHeating;
  bool? BabySeat;
  bool? HeatedSeats;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferencesOther({
    this.AppreciatesConversation,
    this.EnjoysMusic,
    this.SmokeFree,
    this.PetFriendly,
    this.WinterTires,
    this.CoolingOrHeating,
    this.BabySeat,
    this.HeatedSeats,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferencesOther.fromJson(Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
    EnjoysMusic = json['EnjoysMusic'];
    SmokeFree = json['SmokeFree'];
    PetFriendly = json['PetFriendly'];
    WinterTires = json['WinterTires'];
    CoolingOrHeating = json['CoolingOrHeating'];
    BabySeat = json['BabySeat'];
    HeatedSeats = json['HeatedSeats'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    data['EnjoysMusic'] = EnjoysMusic;
    data['SmokeFree'] = SmokeFree;
    data['PetFriendly'] = PetFriendly;
    data['WinterTires'] = WinterTires;
    data['CoolingOrHeating'] = CoolingOrHeating;
    data['BabySeat'] = BabySeat;
    data['HeatedSeats'] = HeatedSeats;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferences {
/*
{
  "other": {
    "AppreciatesConversation": false,
    "EnjoysMusic": false,
    "SmokeFree": false,
    "PetFriendly": false,
    "WinterTires": false,
    "CoolingOrHeating": false,
    "BabySeat": false,
    "HeatedSeats": false
  },
  "luggageType": null
} 
*/

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferencesOther? other;
  String? luggageType;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferences({
    this.other,
    this.luggageType,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferences.fromJson(Map<String, dynamic> json) {
    other = (json['other'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferencesOther.fromJson(json['other']) : null;
    luggageType = json['luggageType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (other != null) {
      data['other'] = other!.toJson();
    }
    data['luggageType'] = luggageType;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsReturnTrip {
/*
{
  "returnTripId": null,
  "isReturnTrip": false,
  "returnDate": null,
  "returnTime": null
} 
*/

  String? returnTripId;
  bool? isReturnTrip;
  String? returnDate;
  String? returnTime;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsReturnTrip({
    this.returnTripId,
    this.isReturnTrip,
    this.returnDate,
    this.returnTime,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsReturnTrip.fromJson(Map<String, dynamic> json) {
    returnTripId = json['returnTripId']?.toString();
    isReturnTrip = json['isReturnTrip'];
    returnDate = json['returnDate']?.toString();
    returnTime = json['returnTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['returnTripId'] = returnTripId;
    data['isReturnTrip'] = isReturnTrip;
    data['returnDate'] = returnDate;
    data['returnTime'] = returnTime;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsRecurringTrip {
/*
{
  "recurringTripIds": [
    ""
  ],
  "recurringTripDays": [
    1
  ],
  "isRecurringTripEnabled": false
} 
*/

  List<String?>? recurringTripIds;
  List<int?>? recurringTripDays;
  bool? isRecurringTripEnabled;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsRecurringTrip({
    this.recurringTripIds,
    this.recurringTripDays,
    this.isRecurringTripEnabled,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsRecurringTrip.fromJson(Map<String, dynamic> json) {
  if (json['recurringTripIds'] != null) {
  final v = json['recurringTripIds'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    recurringTripIds = arr0;
    }
  if (json['recurringTripDays'] != null) {
  final v = json['recurringTripDays'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    recurringTripDays = arr0;
    }
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recurringTripIds != null) {
      final v = recurringTripIds;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripIds'] = arr0;
    }
    if (recurringTripDays != null) {
      final v = recurringTripDays;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripDays'] = arr0;
    }
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsDestination {
/*
{
  "name": "Ontario International Airport (ONT), Ontario",
  "type": "Point",
  "coordinates": [
    -117.5980922
  ]
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsDestination({
    this.name,
    this.type,
    this.coordinates,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsOrigin {
/*
{
  "name": "1 Mills Cir, Ontario",
  "type": "Point",
  "coordinates": [
    -117.551993
  ],
  "originDestinationFair": null
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;
  String? originDestinationFair;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsOrigin({
    this.name,
    this.type,
    this.coordinates,
    this.originDestinationFair,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originDestinationFair = json['originDestinationFair']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originDestinationFair'] = originDestinationFair;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails {
/*
{
  "_id": "6639c92158249d84ebc50780",
  "riderId": "661d10c3cea4346b0ee267d3",
  "origin": {
    "name": "1 Mills Cir, Ontario",
    "type": "Point",
    "coordinates": [
      -117.551993
    ],
    "originDestinationFair": null
  },
  "destination": {
    "name": "Ontario International Airport (ONT), Ontario",
    "type": "Point",
    "coordinates": [
      -117.5980922
    ]
  },
  "tripType": null,
  "recurringTrip": {
    "recurringTripIds": [
      ""
    ],
    "recurringTripDays": [
      1
    ],
    "isRecurringTripEnabled": false
  },
  "date": "2024-05-07T00:00:00.000Z",
  "time": "11:50 AM",
  "returnTrip": {
    "returnTripId": null,
    "isReturnTrip": false,
    "returnDate": null,
    "returnTime": null
  },
  "arrivalDate": null,
  "arrivalTime": null,
  "seatAvailable": 1,
  "preferences": {
    "other": {
      "AppreciatesConversation": false,
      "EnjoysMusic": false,
      "SmokeFree": false,
      "PetFriendly": false,
      "WinterTires": false,
      "CoolingOrHeating": false,
      "BabySeat": false,
      "HeatedSeats": false
    },
    "luggageType": null
  },
  "isStarted": false,
  "isCompleted": false,
  "isCancelled": false,
  "description": "need a ride to airport",
  "createdAt": "2024-05-07T06:24:33.031Z",
  "updatedAt": "2024-05-07T06:24:33.031Z"
} 
*/

  String? Id;
  String? riderId;
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsOrigin? origin;
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsDestination? destination;
  String? tripType;
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsRecurringTrip? recurringTrip;
  String? date;
  String? time;
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsReturnTrip? returnTrip;
  String? arrivalDate;
  String? arrivalTime;
  int? seatAvailable;
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferences? preferences;
  bool? isStarted;
  bool? isCompleted;
  bool? isCancelled;
  String? description;
  String? createdAt;
  String? updatedAt;

  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails({
    this.Id,
    this.riderId,
    this.origin,
    this.destination,
    this.tripType,
    this.recurringTrip,
    this.date,
    this.time,
    this.returnTrip,
    this.arrivalDate,
    this.arrivalTime,
    this.seatAvailable,
    this.preferences,
    this.isStarted,
    this.isCompleted,
    this.isCancelled,
    this.description,
    this.createdAt,
    this.updatedAt,
  });
  BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    riderId = json['riderId']?.toString();
    origin = (json['origin'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsDestination.fromJson(json['destination']) : null;
    tripType = json['tripType']?.toString();
    recurringTrip = (json['recurringTrip'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsRecurringTrip.fromJson(json['recurringTrip']) : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    returnTrip = (json['returnTrip'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsReturnTrip.fromJson(json['returnTrip']) : null;
    arrivalDate = json['arrivalDate']?.toString();
    arrivalTime = json['arrivalTime']?.toString();
    seatAvailable = json['seatAvailable']?.toInt();
    preferences = (json['preferences'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetailsPreferences.fromJson(json['preferences']) : null;
    isStarted = json['isStarted'];
    isCompleted = json['isCompleted'];
    isCancelled = json['isCancelled'];
    description = json['description']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['riderId'] = riderId;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    data['tripType'] = tripType;
    if (recurringTrip != null) {
      data['recurringTrip'] = recurringTrip!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    if (returnTrip != null) {
      data['returnTrip'] = returnTrip!.toJson();
    }
    data['arrivalDate'] = arrivalDate;
    data['arrivalTime'] = arrivalTime;
    data['seatAvailable'] = seatAvailable;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['isStarted'] = isStarted;
    data['isCompleted'] = isCompleted;
    data['isCancelled'] = isCancelled;
    data['description'] = description;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersProfilePic {
/*
{
  "key": "usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg"
} 
*/

  String? key;
  String? url;

  BookingDetailModelDataDriverBookingDetailsRidersProfilePic({
    this.key,
    this.url,
  });
  BookingDetailModelDataDriverBookingDetailsRidersProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersIdPic {
/*
{
  "key": "idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg"
} 
*/

  String? key;
  String? url;

  BookingDetailModelDataDriverBookingDetailsRidersIdPic({
    this.key,
    this.url,
  });
  BookingDetailModelDataDriverBookingDetailsRidersIdPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRidersNotificationPreferences {
/*
{
  "trip": true,
  "alerts": true,
  "payments": true,
  "transactions": true,
  "offers": true
} 
*/

  bool? trip;
  bool? alerts;
  bool? payments;
  bool? transactions;
  bool? offers;

  BookingDetailModelDataDriverBookingDetailsRidersNotificationPreferences({
    this.trip,
    this.alerts,
    this.payments,
    this.transactions,
    this.offers,
  });
  BookingDetailModelDataDriverBookingDetailsRidersNotificationPreferences.fromJson(Map<String, dynamic> json) {
    trip = json['trip'];
    alerts = json['alerts'];
    payments = json['payments'];
    transactions = json['transactions'];
    offers = json['offers'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    data['alerts'] = alerts;
    data['payments'] = payments;
    data['transactions'] = transactions;
    data['offers'] = offers;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRiders {
/*
{
  "_id": "661d10c3cea4346b0ee267d3",
  "pinkMode": false,
  "fullName": "Ria",
  "phone": "+11212121212",
  "email": "ria@test.com",
  "city": "Rajkot",
  "dob": "2000-04-20",
  "gender": "Female",
  "isDriver": false,
  "referralCode": "S0175P2893",
  "profileStatus": true,
  "vehicleStatus": false,
  "status": "active",
  "wallet": 0,
  "notificationPreferences": {
    "trip": true,
    "alerts": true,
    "payments": true,
    "transactions": true,
    "offers": true
  },
  "firebaseUid": "YfTcEdNqhHPbYWY5bZzQxy5EwHG2",
  "firebaseSignInProvider": "phone",
  "rating": 0,
  "createdAt": "2024-04-15T11:34:27.422Z",
  "updatedAt": "2024-05-08T07:46:48.365Z",
  "idPic": {
    "key": "idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg"
  },
  "profilePic": {
    "key": "usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg"
  },
  "totalRides": 1,
  "isRegister": true,
  "role": "user",
  "riderBookingDetails": [
    {
      "_id": "6639c92158249d84ebc50780",
      "riderId": "661d10c3cea4346b0ee267d3",
      "origin": {
        "name": "1 Mills Cir, Ontario",
        "type": "Point",
        "coordinates": [
          -117.551993
        ],
        "originDestinationFair": null
      },
      "destination": {
        "name": "Ontario International Airport (ONT), Ontario",
        "type": "Point",
        "coordinates": [
          -117.5980922
        ]
      },
      "tripType": null,
      "recurringTrip": {
        "recurringTripIds": [
          ""
        ],
        "recurringTripDays": [
          1
        ],
        "isRecurringTripEnabled": false
      },
      "date": "2024-05-07T00:00:00.000Z",
      "time": "11:50 AM",
      "returnTrip": {
        "returnTripId": null,
        "isReturnTrip": false,
        "returnDate": null,
        "returnTime": null
      },
      "arrivalDate": null,
      "arrivalTime": null,
      "seatAvailable": 1,
      "preferences": {
        "other": {
          "AppreciatesConversation": false,
          "EnjoysMusic": false,
          "SmokeFree": false,
          "PetFriendly": false,
          "WinterTires": false,
          "CoolingOrHeating": false,
          "BabySeat": false,
          "HeatedSeats": false
        },
        "luggageType": null
      },
      "isStarted": false,
      "isCompleted": false,
      "isCancelled": false,
      "description": "need a ride to airport",
      "createdAt": "2024-05-07T06:24:33.031Z",
      "updatedAt": "2024-05-07T06:24:33.031Z"
    }
  ]
} 
*/

  String? Id;
  bool? pinkMode;
  String? fullName;
  String? phone;
  String? email;
  String? city;
  String? dob;
  String? gender;
  bool? isDriver;
  String? referralCode;
  bool? profileStatus;
  bool? vehicleStatus;
  String? status;
  int? wallet;
  BookingDetailModelDataDriverBookingDetailsRidersNotificationPreferences? notificationPreferences;
  String? firebaseUid;
  String? firebaseSignInProvider;
  int? rating;
  String? createdAt;
  String? updatedAt;
  BookingDetailModelDataDriverBookingDetailsRidersIdPic? idPic;
  BookingDetailModelDataDriverBookingDetailsRidersProfilePic? profilePic;
  int? totalRides;
  bool? isRegister;
  String? role;
  List<BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails?>? riderBookingDetails;

  BookingDetailModelDataDriverBookingDetailsRiders({
    this.Id,
    this.pinkMode,
    this.fullName,
    this.phone,
    this.email,
    this.city,
    this.dob,
    this.gender,
    this.isDriver,
    this.referralCode,
    this.profileStatus,
    this.vehicleStatus,
    this.status,
    this.wallet,
    this.notificationPreferences,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.rating,
    this.createdAt,
    this.updatedAt,
    this.idPic,
    this.profilePic,
    this.totalRides,
    this.isRegister,
    this.role,
    this.riderBookingDetails,
  });
  BookingDetailModelDataDriverBookingDetailsRiders.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    pinkMode = json['pinkMode'];
    fullName = json['fullName']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    city = json['city']?.toString();
    dob = json['dob']?.toString();
    gender = json['gender']?.toString();
    isDriver = json['isDriver'];
    referralCode = json['referralCode']?.toString();
    profileStatus = json['profileStatus'];
    vehicleStatus = json['vehicleStatus'];
    status = json['status']?.toString();
    wallet = json['wallet']?.toInt();
    notificationPreferences = (json['notificationPreferences'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersNotificationPreferences.fromJson(json['notificationPreferences']) : null;
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    rating = json['rating']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    idPic = (json['idPic'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersIdPic.fromJson(json['idPic']) : null;
    profilePic = (json['profilePic'] != null) ? BookingDetailModelDataDriverBookingDetailsRidersProfilePic.fromJson(json['profilePic']) : null;
    totalRides = json['totalRides']?.toInt();
    isRegister = json['isRegister'];
    role = json['role']?.toString();
  if (json['riderBookingDetails'] != null) {
  final v = json['riderBookingDetails'];
  final arr0 = <BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails>[];
  v.forEach((v) {
  arr0.add(BookingDetailModelDataDriverBookingDetailsRidersRiderBookingDetails.fromJson(v));
  });
    riderBookingDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['pinkMode'] = pinkMode;
    data['fullName'] = fullName;
    data['phone'] = phone;
    data['email'] = email;
    data['city'] = city;
    data['dob'] = dob;
    data['gender'] = gender;
    data['isDriver'] = isDriver;
    data['referralCode'] = referralCode;
    data['profileStatus'] = profileStatus;
    data['vehicleStatus'] = vehicleStatus;
    data['status'] = status;
    data['wallet'] = wallet;
    if (notificationPreferences != null) {
      data['notificationPreferences'] = notificationPreferences!.toJson();
    }
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['rating'] = rating;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (idPic != null) {
      data['idPic'] = idPic!.toJson();
    }
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['totalRides'] = totalRides;
    data['isRegister'] = isRegister;
    data['role'] = role;
    if (riderBookingDetails != null) {
      final v = riderBookingDetails;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['riderBookingDetails'] = arr0;
    }
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsPreferencesOther {
/*
{
  "AppreciatesConversation": false,
  "EnjoysMusic": false,
  "SmokeFree": true,
  "PetFriendly": true,
  "WinterTires": false,
  "CoolingOrHeating": false,
  "BabySeat": false,
  "HeatedSeats": false
} 
*/

  bool? AppreciatesConversation;
  bool? EnjoysMusic;
  bool? SmokeFree;
  bool? PetFriendly;
  bool? WinterTires;
  bool? CoolingOrHeating;
  bool? BabySeat;
  bool? HeatedSeats;

  BookingDetailModelDataDriverBookingDetailsPreferencesOther({
    this.AppreciatesConversation,
    this.EnjoysMusic,
    this.SmokeFree,
    this.PetFriendly,
    this.WinterTires,
    this.CoolingOrHeating,
    this.BabySeat,
    this.HeatedSeats,
  });
  BookingDetailModelDataDriverBookingDetailsPreferencesOther.fromJson(Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
    EnjoysMusic = json['EnjoysMusic'];
    SmokeFree = json['SmokeFree'];
    PetFriendly = json['PetFriendly'];
    WinterTires = json['WinterTires'];
    CoolingOrHeating = json['CoolingOrHeating'];
    BabySeat = json['BabySeat'];
    HeatedSeats = json['HeatedSeats'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    data['EnjoysMusic'] = EnjoysMusic;
    data['SmokeFree'] = SmokeFree;
    data['PetFriendly'] = PetFriendly;
    data['WinterTires'] = WinterTires;
    data['CoolingOrHeating'] = CoolingOrHeating;
    data['BabySeat'] = BabySeat;
    data['HeatedSeats'] = HeatedSeats;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsPreferences {
/*
{
  "luggageType": "M",
  "other": {
    "AppreciatesConversation": false,
    "EnjoysMusic": false,
    "SmokeFree": true,
    "PetFriendly": true,
    "WinterTires": false,
    "CoolingOrHeating": false,
    "BabySeat": false,
    "HeatedSeats": false
  }
} 
*/

  String? luggageType;
  BookingDetailModelDataDriverBookingDetailsPreferencesOther? other;

  BookingDetailModelDataDriverBookingDetailsPreferences({
    this.luggageType,
    this.other,
  });
  BookingDetailModelDataDriverBookingDetailsPreferences.fromJson(Map<String, dynamic> json) {
    luggageType = json['luggageType']?.toString();
    other = (json['other'] != null) ? BookingDetailModelDataDriverBookingDetailsPreferencesOther.fromJson(json['other']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['luggageType'] = luggageType;
    if (other != null) {
      data['other'] = other!.toJson();
    }
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsReturnTrip {
/*
{
  "returnTripId": "6639b92358249d84ebc5067a",
  "isReturnTrip": true,
  "returnDate": "2024-05-08T00:00:00.000Z",
  "returnTime": "10:45 AM"
} 
*/

  String? returnTripId;
  bool? isReturnTrip;
  String? returnDate;
  String? returnTime;

  BookingDetailModelDataDriverBookingDetailsReturnTrip({
    this.returnTripId,
    this.isReturnTrip,
    this.returnDate,
    this.returnTime,
  });
  BookingDetailModelDataDriverBookingDetailsReturnTrip.fromJson(Map<String, dynamic> json) {
    returnTripId = json['returnTripId']?.toString();
    isReturnTrip = json['isReturnTrip'];
    returnDate = json['returnDate']?.toString();
    returnTime = json['returnTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['returnTripId'] = returnTripId;
    data['isReturnTrip'] = isReturnTrip;
    data['returnDate'] = returnDate;
    data['returnTime'] = returnTime;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsRecurringTrip {
/*
{
  "recurringTripDays": [
    1
  ],
  "recurringTripIds": [
    ""
  ],
  "isRecurringTripEnabled": false
} 
*/

  List<int?>? recurringTripDays;
  List<String?>? recurringTripIds;
  bool? isRecurringTripEnabled;

  BookingDetailModelDataDriverBookingDetailsRecurringTrip({
    this.recurringTripDays,
    this.recurringTripIds,
    this.isRecurringTripEnabled,
  });
  BookingDetailModelDataDriverBookingDetailsRecurringTrip.fromJson(Map<String, dynamic> json) {
  if (json['recurringTripDays'] != null) {
  final v = json['recurringTripDays'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    recurringTripDays = arr0;
    }
  if (json['recurringTripIds'] != null) {
  final v = json['recurringTripIds'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    recurringTripIds = arr0;
    }
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recurringTripDays != null) {
      final v = recurringTripDays;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripDays'] = arr0;
    }
    if (recurringTripIds != null) {
      final v = recurringTripIds;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['recurringTripIds'] = arr0;
    }
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsStops {
/*
{
  "name": "",
  "type": "Point",
  "coordinates": [
    0
  ],
  "originToStopFair": null,
  "stopToStopFair": null,
  "stopTodestinationFair": null,
  "_id": "6639b92358249d84ebc5067f"
} 
*/

  String? name;
  String? type;
  List<int?>? coordinates;
  String? originToStopFair;
  String? stopToStopFair;
  String? stopTodestinationFair;
  String? Id;

  BookingDetailModelDataDriverBookingDetailsStops({
    this.name,
    this.type,
    this.coordinates,
    this.originToStopFair,
    this.stopToStopFair,
    this.stopTodestinationFair,
    this.Id,
  });
  BookingDetailModelDataDriverBookingDetailsStops.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <int>[];
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    coordinates = arr0;
    }
    originToStopFair = json['originToStopFair']?.toString();
    stopToStopFair = json['stopToStopFair']?.toString();
    stopTodestinationFair = json['stopTodestinationFair']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originToStopFair'] = originToStopFair;
    data['stopToStopFair'] = stopToStopFair;
    data['stopTodestinationFair'] = stopTodestinationFair;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsDestination {
/*
{
  "name": "Ontario International Airport (ONT), Ontario",
  "type": "Point",
  "coordinates": [
    -117.5980922
  ]
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;

  BookingDetailModelDataDriverBookingDetailsDestination({
    this.name,
    this.type,
    this.coordinates,
  });
  BookingDetailModelDataDriverBookingDetailsDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetailsOrigin {
/*
{
  "name": "1 Mills Cir, Ontario",
  "type": "Point",
  "coordinates": [
    -117.551993
  ],
  "originDestinationFair": "12"
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;
  String? originDestinationFair;

  BookingDetailModelDataDriverBookingDetailsOrigin({
    this.name,
    this.type,
    this.coordinates,
    this.originDestinationFair,
  });
  BookingDetailModelDataDriverBookingDetailsOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originDestinationFair = json['originDestinationFair']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originDestinationFair'] = originDestinationFair;
    return data;
  }
}

class BookingDetailModelDataDriverBookingDetails {
/*
{
  "_id": "6639b92358249d84ebc5067e",
  "driverId": "6639b78f58249d84ebc5062f",
  "origin": {
    "name": "1 Mills Cir, Ontario",
    "type": "Point",
    "coordinates": [
      -117.551993
    ],
    "originDestinationFair": "12"
  },
  "destination": {
    "name": "Ontario International Airport (ONT), Ontario",
    "type": "Point",
    "coordinates": [
      -117.5980922
    ]
  },
  "stops": [
    {
      "name": "",
      "type": "Point",
      "coordinates": [
        0
      ],
      "originToStopFair": null,
      "stopToStopFair": null,
      "stopTodestinationFair": null,
      "_id": "6639b92358249d84ebc5067f"
    }
  ],
  "tripType": "oneTime",
  "recurringTrip": {
    "recurringTripDays": [
      1
    ],
    "recurringTripIds": [
      ""
    ],
    "isRecurringTripEnabled": false
  },
  "date": "2024-05-08T00:00:00.000Z",
  "time": "11:44 AM",
  "returnTrip": {
    "returnTripId": "6639b92358249d84ebc5067a",
    "isReturnTrip": true,
    "returnDate": "2024-05-08T00:00:00.000Z",
    "returnTime": "10:45 AM"
  },
  "arrivalDate": null,
  "arrivalTime": null,
  "seatAvailable": 3,
  "preferences": {
    "luggageType": "M",
    "other": {
      "AppreciatesConversation": false,
      "EnjoysMusic": false,
      "SmokeFree": true,
      "PetFriendly": true,
      "WinterTires": false,
      "CoolingOrHeating": false,
      "BabySeat": false,
      "HeatedSeats": false
    }
  },
  "isStarted": false,
  "isCompleted": false,
  "isCancelled": false,
  "riders": [
    {
      "_id": "661d10c3cea4346b0ee267d3",
      "pinkMode": false,
      "fullName": "Ria",
      "phone": "+11212121212",
      "email": "ria@test.com",
      "city": "Rajkot",
      "dob": "2000-04-20",
      "gender": "Female",
      "isDriver": false,
      "referralCode": "S0175P2893",
      "profileStatus": true,
      "vehicleStatus": false,
      "status": "active",
      "wallet": 0,
      "notificationPreferences": {
        "trip": true,
        "alerts": true,
        "payments": true,
        "transactions": true,
        "offers": true
      },
      "firebaseUid": "YfTcEdNqhHPbYWY5bZzQxy5EwHG2",
      "firebaseSignInProvider": "phone",
      "rating": 0,
      "createdAt": "2024-04-15T11:34:27.422Z",
      "updatedAt": "2024-05-08T07:46:48.365Z",
      "idPic": {
        "key": "idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg"
      },
      "profilePic": {
        "key": "usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg"
      },
      "totalRides": 1,
      "isRegister": true,
      "role": "user",
      "riderBookingDetails": [
        {
          "_id": "6639c92158249d84ebc50780",
          "riderId": "661d10c3cea4346b0ee267d3",
          "origin": {
            "name": "1 Mills Cir, Ontario",
            "type": "Point",
            "coordinates": [
              -117.551993
            ],
            "originDestinationFair": null
          },
          "destination": {
            "name": "Ontario International Airport (ONT), Ontario",
            "type": "Point",
            "coordinates": [
              -117.5980922
            ]
          },
          "tripType": null,
          "recurringTrip": {
            "recurringTripIds": [
              ""
            ],
            "recurringTripDays": [
              1
            ],
            "isRecurringTripEnabled": false
          },
          "date": "2024-05-07T00:00:00.000Z",
          "time": "11:50 AM",
          "returnTrip": {
            "returnTripId": null,
            "isReturnTrip": false,
            "returnDate": null,
            "returnTime": null
          },
          "arrivalDate": null,
          "arrivalTime": null,
          "seatAvailable": 1,
          "preferences": {
            "other": {
              "AppreciatesConversation": false,
              "EnjoysMusic": false,
              "SmokeFree": false,
              "PetFriendly": false,
              "WinterTires": false,
              "CoolingOrHeating": false,
              "BabySeat": false,
              "HeatedSeats": false
            },
            "luggageType": null
          },
          "isStarted": false,
          "isCompleted": false,
          "isCancelled": false,
          "description": "need a ride to airport",
          "createdAt": "2024-05-07T06:24:33.031Z",
          "updatedAt": "2024-05-07T06:24:33.031Z"
        }
      ]
    }
  ],
  "description": "from ontario mills to ontario airport",
  "createdAt": "2024-05-07T05:16:19.511Z",
  "updatedAt": "2024-05-07T10:28:43.790Z",
  "driverDetails": {
    "_id": "6639b78f58249d84ebc5062f",
    "isRegister": true,
    "pinkMode": false,
    "fullName": "Zen",
    "phone": "+11234512345",
    "email": "zen@test.com",
    "city": "Brampton",
    "profilePic": {
      "key": "usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
      "_id": "6639b83358249d84ebc50638"
    },
    "idPic": {
      "key": "idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
      "_id": "6639b83358249d84ebc50639"
    },
    "dob": "2006-05-12",
    "gender": "Male",
    "isDriver": true,
    "referralCode": "N5213I5793",
    "profileStatus": true,
    "vehicleStatus": true,
    "status": "active",
    "wallet": 0,
    "rating": 0,
    "totalRides": 0,
    "isRecurringTripEnabled": false,
    "notificationPreferences": {
      "trip": true,
      "alerts": true,
      "payments": true,
      "transactions": true,
      "offers": true
    },
    "firebaseUid": "n9XvgstaJCShxg2V5AmREneUYOE2",
    "firebaseSignInProvider": "phone",
    "createdAt": "2024-05-07T05:09:35.528Z",
    "updatedAt": "2024-05-08T09:23:23.028Z",
    "role": "user",
    "vechileDetails": {
      "_id": "6639b8a358249d84ebc5063f",
      "driverId": "6639b78f58249d84ebc5062f",
      "vehiclePic": {
        "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
        "_id": "6639b8a358249d84ebc50640"
      },
      "model": "iuModel",
      "type": "Sedan",
      "color": "Silver",
      "year": 2000,
      "licencePlate": "CA2000",
      "createdAt": "2024-05-07T05:14:11.059Z",
      "updatedAt": "2024-05-07T05:14:11.059Z"
    }
  }
} 
*/

  String? Id;
  String? driverId;
  BookingDetailModelDataDriverBookingDetailsOrigin? origin;
  BookingDetailModelDataDriverBookingDetailsDestination? destination;
  List<BookingDetailModelDataDriverBookingDetailsStops?>? stops;
  String? tripType;
  BookingDetailModelDataDriverBookingDetailsRecurringTrip? recurringTrip;
  String? date;
  String? time;
  BookingDetailModelDataDriverBookingDetailsReturnTrip? returnTrip;
  String? arrivalDate;
  String? arrivalTime;
  int? seatAvailable;
  BookingDetailModelDataDriverBookingDetailsPreferences? preferences;
  bool? isStarted;
  bool? isCompleted;
  bool? isCancelled;
  List<BookingDetailModelDataDriverBookingDetailsRiders?>? riders;
  String? description;
  String? createdAt;
  String? updatedAt;
  BookingDetailModelDataDriverBookingDetailsDriverDetails? driverDetails;

  BookingDetailModelDataDriverBookingDetails({
    this.Id,
    this.driverId,
    this.origin,
    this.destination,
    this.stops,
    this.tripType,
    this.recurringTrip,
    this.date,
    this.time,
    this.returnTrip,
    this.arrivalDate,
    this.arrivalTime,
    this.seatAvailable,
    this.preferences,
    this.isStarted,
    this.isCompleted,
    this.isCancelled,
    this.riders,
    this.description,
    this.createdAt,
    this.updatedAt,
    this.driverDetails,
  });
  BookingDetailModelDataDriverBookingDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    driverId = json['driverId']?.toString();
    origin = (json['origin'] != null) ? BookingDetailModelDataDriverBookingDetailsOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? BookingDetailModelDataDriverBookingDetailsDestination.fromJson(json['destination']) : null;
  if (json['stops'] != null) {
  final v = json['stops'];
  final arr0 = <BookingDetailModelDataDriverBookingDetailsStops>[];
  v.forEach((v) {
  arr0.add(BookingDetailModelDataDriverBookingDetailsStops.fromJson(v));
  });
    stops = arr0;
    }
    tripType = json['tripType']?.toString();
    recurringTrip = (json['recurringTrip'] != null) ? BookingDetailModelDataDriverBookingDetailsRecurringTrip.fromJson(json['recurringTrip']) : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    returnTrip = (json['returnTrip'] != null) ? BookingDetailModelDataDriverBookingDetailsReturnTrip.fromJson(json['returnTrip']) : null;
    arrivalDate = json['arrivalDate']?.toString();
    arrivalTime = json['arrivalTime']?.toString();
    seatAvailable = json['seatAvailable']?.toInt();
    preferences = (json['preferences'] != null) ? BookingDetailModelDataDriverBookingDetailsPreferences.fromJson(json['preferences']) : null;
    isStarted = json['isStarted'];
    isCompleted = json['isCompleted'];
    isCancelled = json['isCancelled'];
  if (json['riders'] != null) {
  final v = json['riders'];
  final arr0 = <BookingDetailModelDataDriverBookingDetailsRiders>[];
  v.forEach((v) {
  arr0.add(BookingDetailModelDataDriverBookingDetailsRiders.fromJson(v));
  });
    riders = arr0;
    }
    description = json['description']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    driverDetails = (json['driverDetails'] != null) ? BookingDetailModelDataDriverBookingDetailsDriverDetails.fromJson(json['driverDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['driverId'] = driverId;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (stops != null) {
      final v = stops;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['stops'] = arr0;
    }
    data['tripType'] = tripType;
    if (recurringTrip != null) {
      data['recurringTrip'] = recurringTrip!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    if (returnTrip != null) {
      data['returnTrip'] = returnTrip!.toJson();
    }
    data['arrivalDate'] = arrivalDate;
    data['arrivalTime'] = arrivalTime;
    data['seatAvailable'] = seatAvailable;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['isStarted'] = isStarted;
    data['isCompleted'] = isCompleted;
    data['isCancelled'] = isCancelled;
    if (riders != null) {
      final v = riders;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['riders'] = arr0;
    }
    data['description'] = description;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (driverDetails != null) {
      data['driverDetails'] = driverDetails!.toJson();
    }
    return data;
  }
}

class BookingDetailModelDataDropOffStatus {
/*
{
  "isDropOff": false
} 
*/

  bool? isDropOff;

  BookingDetailModelDataDropOffStatus({
    this.isDropOff,
  });
  BookingDetailModelDataDropOffStatus.fromJson(Map<String, dynamic> json) {
    isDropOff = json['isDropOff'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isDropOff'] = isDropOff;
    return data;
  }
}

class BookingDetailModelDataPickUpStatus {
/*
{
  "isPickUp": false
} 
*/

  bool? isPickUp;

  BookingDetailModelDataPickUpStatus({
    this.isPickUp,
  });
  BookingDetailModelDataPickUpStatus.fromJson(Map<String, dynamic> json) {
    isPickUp = json['isPickUp'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isPickUp'] = isPickUp;
    return data;
  }
}

class BookingDetailModelData {
/*
{
  "_id": "6639e18358249d84ebc509da",
  "driverRideId": "6639b92358249d84ebc5067e",
  "riderRideId": "6639c92158249d84ebc50780",
  "distance": "0.0",
  "cancelByDriver": false,
  "cancelByRider": false,
  "confirmByRider": true,
  "confirmByDriver": true,
  "pickUpStatus": {
    "isPickUp": false
  },
  "dropOffStatus": {
    "isDropOff": false
  },
  "isCompleted": false,
  "driverId": "6639b78f58249d84ebc5062f",
  "createdAt": "2024-05-07T08:08:35.750Z",
  "updatedAt": "2024-05-07T10:28:43.626Z",
  "driverBookingDetails": {
    "_id": "6639b92358249d84ebc5067e",
    "driverId": "6639b78f58249d84ebc5062f",
    "origin": {
      "name": "1 Mills Cir, Ontario",
      "type": "Point",
      "coordinates": [
        -117.551993
      ],
      "originDestinationFair": "12"
    },
    "destination": {
      "name": "Ontario International Airport (ONT), Ontario",
      "type": "Point",
      "coordinates": [
        -117.5980922
      ]
    },
    "stops": [
      {
        "name": "",
        "type": "Point",
        "coordinates": [
          0
        ],
        "originToStopFair": null,
        "stopToStopFair": null,
        "stopTodestinationFair": null,
        "_id": "6639b92358249d84ebc5067f"
      }
    ],
    "tripType": "oneTime",
    "recurringTrip": {
      "recurringTripDays": [
        1
      ],
      "recurringTripIds": [
        ""
      ],
      "isRecurringTripEnabled": false
    },
    "date": "2024-05-08T00:00:00.000Z",
    "time": "11:44 AM",
    "returnTrip": {
      "returnTripId": "6639b92358249d84ebc5067a",
      "isReturnTrip": true,
      "returnDate": "2024-05-08T00:00:00.000Z",
      "returnTime": "10:45 AM"
    },
    "arrivalDate": null,
    "arrivalTime": null,
    "seatAvailable": 3,
    "preferences": {
      "luggageType": "M",
      "other": {
        "AppreciatesConversation": false,
        "EnjoysMusic": false,
        "SmokeFree": true,
        "PetFriendly": true,
        "WinterTires": false,
        "CoolingOrHeating": false,
        "BabySeat": false,
        "HeatedSeats": false
      }
    },
    "isStarted": false,
    "isCompleted": false,
    "isCancelled": false,
    "riders": [
      {
        "_id": "661d10c3cea4346b0ee267d3",
        "pinkMode": false,
        "fullName": "Ria",
        "phone": "+11212121212",
        "email": "ria@test.com",
        "city": "Rajkot",
        "dob": "2000-04-20",
        "gender": "Female",
        "isDriver": false,
        "referralCode": "S0175P2893",
        "profileStatus": true,
        "vehicleStatus": false,
        "status": "active",
        "wallet": 0,
        "notificationPreferences": {
          "trip": true,
          "alerts": true,
          "payments": true,
          "transactions": true,
          "offers": true
        },
        "firebaseUid": "YfTcEdNqhHPbYWY5bZzQxy5EwHG2",
        "firebaseSignInProvider": "phone",
        "rating": 0,
        "createdAt": "2024-04-15T11:34:27.422Z",
        "updatedAt": "2024-05-08T07:46:48.365Z",
        "idPic": {
          "key": "idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg"
        },
        "profilePic": {
          "key": "usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg"
        },
        "totalRides": 1,
        "isRegister": true,
        "role": "user",
        "riderBookingDetails": [
          {
            "_id": "6639c92158249d84ebc50780",
            "riderId": "661d10c3cea4346b0ee267d3",
            "origin": {
              "name": "1 Mills Cir, Ontario",
              "type": "Point",
              "coordinates": [
                -117.551993
              ],
              "originDestinationFair": null
            },
            "destination": {
              "name": "Ontario International Airport (ONT), Ontario",
              "type": "Point",
              "coordinates": [
                -117.5980922
              ]
            },
            "tripType": null,
            "recurringTrip": {
              "recurringTripIds": [
                ""
              ],
              "recurringTripDays": [
                1
              ],
              "isRecurringTripEnabled": false
            },
            "date": "2024-05-07T00:00:00.000Z",
            "time": "11:50 AM",
            "returnTrip": {
              "returnTripId": null,
              "isReturnTrip": false,
              "returnDate": null,
              "returnTime": null
            },
            "arrivalDate": null,
            "arrivalTime": null,
            "seatAvailable": 1,
            "preferences": {
              "other": {
                "AppreciatesConversation": false,
                "EnjoysMusic": false,
                "SmokeFree": false,
                "PetFriendly": false,
                "WinterTires": false,
                "CoolingOrHeating": false,
                "BabySeat": false,
                "HeatedSeats": false
              },
              "luggageType": null
            },
            "isStarted": false,
            "isCompleted": false,
            "isCancelled": false,
            "description": "need a ride to airport",
            "createdAt": "2024-05-07T06:24:33.031Z",
            "updatedAt": "2024-05-07T06:24:33.031Z"
          }
        ]
      }
    ],
    "description": "from ontario mills to ontario airport",
    "createdAt": "2024-05-07T05:16:19.511Z",
    "updatedAt": "2024-05-07T10:28:43.790Z",
    "driverDetails": {
      "_id": "6639b78f58249d84ebc5062f",
      "isRegister": true,
      "pinkMode": false,
      "fullName": "Zen",
      "phone": "+11234512345",
      "email": "zen@test.com",
      "city": "Brampton",
      "profilePic": {
        "key": "usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
        "_id": "6639b83358249d84ebc50638"
      },
      "idPic": {
        "key": "idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
        "_id": "6639b83358249d84ebc50639"
      },
      "dob": "2006-05-12",
      "gender": "Male",
      "isDriver": true,
      "referralCode": "N5213I5793",
      "profileStatus": true,
      "vehicleStatus": true,
      "status": "active",
      "wallet": 0,
      "rating": 0,
      "totalRides": 0,
      "isRecurringTripEnabled": false,
      "notificationPreferences": {
        "trip": true,
        "alerts": true,
        "payments": true,
        "transactions": true,
        "offers": true
      },
      "firebaseUid": "n9XvgstaJCShxg2V5AmREneUYOE2",
      "firebaseSignInProvider": "phone",
      "createdAt": "2024-05-07T05:09:35.528Z",
      "updatedAt": "2024-05-08T09:23:23.028Z",
      "role": "user",
      "vechileDetails": {
        "_id": "6639b8a358249d84ebc5063f",
        "driverId": "6639b78f58249d84ebc5062f",
        "vehiclePic": {
          "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
          "_id": "6639b8a358249d84ebc50640"
        },
        "model": "iuModel",
        "type": "Sedan",
        "color": "Silver",
        "year": 2000,
        "licencePlate": "CA2000",
        "createdAt": "2024-05-07T05:14:11.059Z",
        "updatedAt": "2024-05-07T05:14:11.059Z"
      }
    }
  }
} 
*/

  String? Id;
  String? driverRideId;
  String? riderRideId;
  String? distance;
  bool? cancelByDriver;
  bool? cancelByRider;
  bool? confirmByRider;
  bool? confirmByDriver;
  BookingDetailModelDataPickUpStatus? pickUpStatus;
  BookingDetailModelDataDropOffStatus? dropOffStatus;
  bool? isCompleted;
  String? driverId;
  String? createdAt;
  String? updatedAt;
  BookingDetailModelDataDriverBookingDetails? driverBookingDetails;

  BookingDetailModelData({
    this.Id,
    this.driverRideId,
    this.riderRideId,
    this.distance,
    this.cancelByDriver,
    this.cancelByRider,
    this.confirmByRider,
    this.confirmByDriver,
    this.pickUpStatus,
    this.dropOffStatus,
    this.isCompleted,
    this.driverId,
    this.createdAt,
    this.updatedAt,
    this.driverBookingDetails,
  });
  BookingDetailModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    driverRideId = json['driverRideId']?.toString();
    riderRideId = json['riderRideId']?.toString();
    distance = json['distance']?.toString();
    cancelByDriver = json['cancelByDriver'];
    cancelByRider = json['cancelByRider'];
    confirmByRider = json['confirmByRider'];
    confirmByDriver = json['confirmByDriver'];
    pickUpStatus = (json['pickUpStatus'] != null) ? BookingDetailModelDataPickUpStatus.fromJson(json['pickUpStatus']) : null;
    dropOffStatus = (json['dropOffStatus'] != null) ? BookingDetailModelDataDropOffStatus.fromJson(json['dropOffStatus']) : null;
    isCompleted = json['isCompleted'];
    driverId = json['driverId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    driverBookingDetails = (json['driverBookingDetails'] != null) ? BookingDetailModelDataDriverBookingDetails.fromJson(json['driverBookingDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['driverRideId'] = driverRideId;
    data['riderRideId'] = riderRideId;
    data['distance'] = distance;
    data['cancelByDriver'] = cancelByDriver;
    data['cancelByRider'] = cancelByRider;
    data['confirmByRider'] = confirmByRider;
    data['confirmByDriver'] = confirmByDriver;
    if (pickUpStatus != null) {
      data['pickUpStatus'] = pickUpStatus!.toJson();
    }
    if (dropOffStatus != null) {
      data['dropOffStatus'] = dropOffStatus!.toJson();
    }
    data['isCompleted'] = isCompleted;
    data['driverId'] = driverId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (driverBookingDetails != null) {
      data['driverBookingDetails'] = driverBookingDetails!.toJson();
    }
    return data;
  }
}

class BookingDetailModel {
/*
{
  "status": true,
  "message": "Boooking details found.",
  "data": {
    "_id": "6639e18358249d84ebc509da",
    "driverRideId": "6639b92358249d84ebc5067e",
    "riderRideId": "6639c92158249d84ebc50780",
    "distance": "0.0",
    "cancelByDriver": false,
    "cancelByRider": false,
    "confirmByRider": true,
    "confirmByDriver": true,
    "pickUpStatus": {
      "isPickUp": false
    },
    "dropOffStatus": {
      "isDropOff": false
    },
    "isCompleted": false,
    "driverId": "6639b78f58249d84ebc5062f",
    "createdAt": "2024-05-07T08:08:35.750Z",
    "updatedAt": "2024-05-07T10:28:43.626Z",
    "driverBookingDetails": {
      "_id": "6639b92358249d84ebc5067e",
      "driverId": "6639b78f58249d84ebc5062f",
      "origin": {
        "name": "1 Mills Cir, Ontario",
        "type": "Point",
        "coordinates": [
          -117.551993
        ],
        "originDestinationFair": "12"
      },
      "destination": {
        "name": "Ontario International Airport (ONT), Ontario",
        "type": "Point",
        "coordinates": [
          -117.5980922
        ]
      },
      "stops": [
        {
          "name": "",
          "type": "Point",
          "coordinates": [
            0
          ],
          "originToStopFair": null,
          "stopToStopFair": null,
          "stopTodestinationFair": null,
          "_id": "6639b92358249d84ebc5067f"
        }
      ],
      "tripType": "oneTime",
      "recurringTrip": {
        "recurringTripDays": [
          1
        ],
        "recurringTripIds": [
          ""
        ],
        "isRecurringTripEnabled": false
      },
      "date": "2024-05-08T00:00:00.000Z",
      "time": "11:44 AM",
      "returnTrip": {
        "returnTripId": "6639b92358249d84ebc5067a",
        "isReturnTrip": true,
        "returnDate": "2024-05-08T00:00:00.000Z",
        "returnTime": "10:45 AM"
      },
      "arrivalDate": null,
      "arrivalTime": null,
      "seatAvailable": 3,
      "preferences": {
        "luggageType": "M",
        "other": {
          "AppreciatesConversation": false,
          "EnjoysMusic": false,
          "SmokeFree": true,
          "PetFriendly": true,
          "WinterTires": false,
          "CoolingOrHeating": false,
          "BabySeat": false,
          "HeatedSeats": false
        }
      },
      "isStarted": false,
      "isCompleted": false,
      "isCancelled": false,
      "riders": [
        {
          "_id": "661d10c3cea4346b0ee267d3",
          "pinkMode": false,
          "fullName": "Ria",
          "phone": "+11212121212",
          "email": "ria@test.com",
          "city": "Rajkot",
          "dob": "2000-04-20",
          "gender": "Female",
          "isDriver": false,
          "referralCode": "S0175P2893",
          "profileStatus": true,
          "vehicleStatus": false,
          "status": "active",
          "wallet": 0,
          "notificationPreferences": {
            "trip": true,
            "alerts": true,
            "payments": true,
            "transactions": true,
            "offers": true
          },
          "firebaseUid": "YfTcEdNqhHPbYWY5bZzQxy5EwHG2",
          "firebaseSignInProvider": "phone",
          "rating": 0,
          "createdAt": "2024-04-15T11:34:27.422Z",
          "updatedAt": "2024-05-08T07:46:48.365Z",
          "idPic": {
            "key": "idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/bf9018c7-ad37-47f0-b648-075e54474b8f-1000000034.jpg"
          },
          "profilePic": {
            "key": "usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/455bece9-6a35-47bc-9650-0ea542382038-compressed_1000000034.jpg"
          },
          "totalRides": 1,
          "isRegister": true,
          "role": "user",
          "riderBookingDetails": [
            {
              "_id": "6639c92158249d84ebc50780",
              "riderId": "661d10c3cea4346b0ee267d3",
              "origin": {
                "name": "1 Mills Cir, Ontario",
                "type": "Point",
                "coordinates": [
                  -117.551993
                ],
                "originDestinationFair": null
              },
              "destination": {
                "name": "Ontario International Airport (ONT), Ontario",
                "type": "Point",
                "coordinates": [
                  -117.5980922
                ]
              },
              "tripType": null,
              "recurringTrip": {
                "recurringTripIds": [
                  ""
                ],
                "recurringTripDays": [
                  1
                ],
                "isRecurringTripEnabled": false
              },
              "date": "2024-05-07T00:00:00.000Z",
              "time": "11:50 AM",
              "returnTrip": {
                "returnTripId": null,
                "isReturnTrip": false,
                "returnDate": null,
                "returnTime": null
              },
              "arrivalDate": null,
              "arrivalTime": null,
              "seatAvailable": 1,
              "preferences": {
                "other": {
                  "AppreciatesConversation": false,
                  "EnjoysMusic": false,
                  "SmokeFree": false,
                  "PetFriendly": false,
                  "WinterTires": false,
                  "CoolingOrHeating": false,
                  "BabySeat": false,
                  "HeatedSeats": false
                },
                "luggageType": null
              },
              "isStarted": false,
              "isCompleted": false,
              "isCancelled": false,
              "description": "need a ride to airport",
              "createdAt": "2024-05-07T06:24:33.031Z",
              "updatedAt": "2024-05-07T06:24:33.031Z"
            }
          ]
        }
      ],
      "description": "from ontario mills to ontario airport",
      "createdAt": "2024-05-07T05:16:19.511Z",
      "updatedAt": "2024-05-07T10:28:43.790Z",
      "driverDetails": {
        "_id": "6639b78f58249d84ebc5062f",
        "isRegister": true,
        "pinkMode": false,
        "fullName": "Zen",
        "phone": "+11234512345",
        "email": "zen@test.com",
        "city": "Brampton",
        "profilePic": {
          "key": "usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/f8be0e1f-86ca-45d4-af4f-d4c04a83fe47-compressed_3f027cf1-f3a0-47b4-a359-af93fcbd77b54236667115881885527.jpg",
          "_id": "6639b83358249d84ebc50638"
        },
        "idPic": {
          "key": "idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/00e6959a-4cdc-431d-ba58-da857820af92-compressed_6625135b-e7b2-47d0-bee1-c5168a1ff49b8491292186802062625.jpg",
          "_id": "6639b83358249d84ebc50639"
        },
        "dob": "2006-05-12",
        "gender": "Male",
        "isDriver": true,
        "referralCode": "N5213I5793",
        "profileStatus": true,
        "vehicleStatus": true,
        "status": "active",
        "wallet": 0,
        "rating": 0,
        "totalRides": 0,
        "isRecurringTripEnabled": false,
        "notificationPreferences": {
          "trip": true,
          "alerts": true,
          "payments": true,
          "transactions": true,
          "offers": true
        },
        "firebaseUid": "n9XvgstaJCShxg2V5AmREneUYOE2",
        "firebaseSignInProvider": "phone",
        "createdAt": "2024-05-07T05:09:35.528Z",
        "updatedAt": "2024-05-08T09:23:23.028Z",
        "role": "user",
        "vechileDetails": {
          "_id": "6639b8a358249d84ebc5063f",
          "driverId": "6639b78f58249d84ebc5062f",
          "vehiclePic": {
            "key": "vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/vehiclePic/caa69155-4853-4a09-ac08-6584a2a3ee86-compressed_0956573e-9537-48c2-9539-f25f3e1597323162184291488028667.jpg",
            "_id": "6639b8a358249d84ebc50640"
          },
          "model": "iuModel",
          "type": "Sedan",
          "color": "Silver",
          "year": 2000,
          "licencePlate": "CA2000",
          "createdAt": "2024-05-07T05:14:11.059Z",
          "updatedAt": "2024-05-07T05:14:11.059Z"
        }
      }
    }
  }
} 
*/

  bool? status;
  String? message;
  BookingDetailModelData? data;

  BookingDetailModel({
    this.status,
    this.message,
    this.data,
  });
  BookingDetailModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? BookingDetailModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
