///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FindRideModelRidesDetailsDestination {
/*
{
  "name": "ambala",
  "longitude": 77.3231,
  "latitude": 28.569588
} 
*/

  String? name;
  double? longitude;
  double? latitude;

  FindRideModelRidesDetailsDestination({
    this.name,
    this.longitude,
    this.latitude,
  });
  FindRideModelRidesDetailsDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class FindRideModelRidesDetailsOrigin {
/*
{
  "name": "Delhi",
  "longitude": 77.31,
  "latitude": 28.5709
} 
*/

  String? name;
  double? longitude;
  double? latitude;

  FindRideModelRidesDetailsOrigin({
    this.name,
    this.longitude,
    this.latitude,
  });
  FindRideModelRidesDetailsOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class FindRideModelRidesDetails {
/*
{
  "origin": {
    "name": "Delhi",
    "longitude": 77.31,
    "latitude": 28.5709
  },
  "destination": {
    "name": "ambala",
    "longitude": 77.3231,
    "latitude": 28.569588
  },
  "date": "2024-01-02T07:00:17.320+00:00",
  "time": "11:00 AM",
  "seatAvailable": 2
} 
*/

  FindRideModelRidesDetailsOrigin? origin;
  FindRideModelRidesDetailsDestination? destination;
  String? date;
  String? time;
  int? seatAvailable;

  FindRideModelRidesDetails({
    this.origin,
    this.destination,
    this.date,
    this.time,
    this.seatAvailable,
  });
  FindRideModelRidesDetails.fromJson(Map<String, dynamic> json) {
    origin = (json['origin'] != null)
        ? FindRideModelRidesDetailsOrigin.fromJson(json['origin'])
        : null;
    destination = (json['destination'] != null)
        ? FindRideModelRidesDetailsDestination.fromJson(json['destination'])
        : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    seatAvailable = json['seatAvailable']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    data['seatAvailable'] = seatAvailable;
    return data;
  }
}

class FindRideModel {
/*
{
  "ridesDetails": {
    "origin": {
      "name": "Delhi",
      "longitude": 77.31,
      "latitude": 28.5709
    },
    "destination": {
      "name": "ambala",
      "longitude": 77.3231,
      "latitude": 28.569588
    },
    "date": "2024-01-02T07:00:17.320+00:00",
    "time": "11:00 AM",
    "seatAvailable": 2
  }
} 
*/

  FindRideModelRidesDetails? ridesDetails;

  FindRideModel({
    this.ridesDetails,
  });
  FindRideModel.fromJson(Map<String, dynamic> json) {
    ridesDetails = (json['ridesDetails'] != null)
        ? FindRideModelRidesDetails.fromJson(json['ridesDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ridesDetails != null) {
      data['ridesDetails'] = ridesDetails!.toJson();
    }
    return data;
  }
}
