///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MessageListModelChatRoomIdsReciverProfilePic {
/*
{
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
} 
*/

  String? url;

  MessageListModelChatRoomIdsReciverProfilePic({
    this.url,
  });
  MessageListModelChatRoomIdsReciverProfilePic.fromJson(
      Map<String, dynamic> json) {
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    return data;
  }
}

class MessageListModelChatRoomIdsReciver {
/*
{
  "profilePic": {
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
  },
  "_id": "6777895d328052ff77d6eadf",
  "fullName": "Alok Sharma"
} 
*/

  MessageListModelChatRoomIdsReciverProfilePic? profilePic;
  String? Id;
  String? fullName;

  MessageListModelChatRoomIdsReciver({
    this.profilePic,
    this.Id,
    this.fullName,
  });
  MessageListModelChatRoomIdsReciver.fromJson(Map<String, dynamic> json) {
    profilePic = (json['profilePic'] != null)
        ? MessageListModelChatRoomIdsReciverProfilePic.fromJson(
            json['profilePic'])
        : null;
    Id = json['_id']?.toString();
    fullName = json['fullName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['_id'] = Id;
    data['fullName'] = fullName;
    return data;
  }
}

class MessageListModelChatRoomIdsRidesDetailsDestination {
/*
{
  "name": "Kitchener, ON, Canada",
  "coordinates": [
    "-80.4925337"
  ]
} 
*/

  String? name;
  List<String?>? coordinates;

  MessageListModelChatRoomIdsRidesDetailsDestination({
    this.name,
    this.coordinates,
  });
  MessageListModelChatRoomIdsRidesDetailsDestination.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class MessageListModelChatRoomIdsRidesDetailsOrigin {
/*
{
  "name": "London, ON, Canada",
  "coordinates": [
    "-81.2452768"
  ]
} 
*/

  String? name;
  List<String?>? coordinates;

  MessageListModelChatRoomIdsRidesDetailsOrigin({
    this.name,
    this.coordinates,
  });
  MessageListModelChatRoomIdsRidesDetailsOrigin.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class MessageListModelChatRoomIdsRidesDetails {
/*
{
  "origin": {
    "name": "London, ON, Canada",
    "coordinates": [
      "-81.2452768"
    ]
  },
  "destination": {
    "name": "Kitchener, ON, Canada",
    "coordinates": [
      "-80.4925337"
    ]
  },
  "date": "2025-01-26T13:00:00.000Z",
  "time": "2025-01-26T13:00:00.000Z",
  "price": 12,
  "seatAvailable": 4,
  "description": "",
  "pinkMode": false,
  "_id": "6790829bd0359bf954d67acc"
} 
*/

  MessageListModelChatRoomIdsRidesDetailsOrigin? origin;
  MessageListModelChatRoomIdsRidesDetailsDestination? destination;
  String? date;
  String? time;
  int? price;
  int? seatAvailable;
  String? description;
  bool? pinkMode;
  String? Id;

  MessageListModelChatRoomIdsRidesDetails({
    this.origin,
    this.destination,
    this.date,
    this.time,
    this.price,
    this.seatAvailable,
    this.description,
    this.pinkMode,
    this.Id,
  });
  MessageListModelChatRoomIdsRidesDetails.fromJson(Map<String, dynamic> json) {
    origin = (json['origin'] != null)
        ? MessageListModelChatRoomIdsRidesDetailsOrigin.fromJson(json['origin'])
        : null;
    destination = (json['destination'] != null)
        ? MessageListModelChatRoomIdsRidesDetailsDestination.fromJson(
            json['destination'])
        : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    price = json['price']?.toInt();
    seatAvailable = json['seatAvailable']?.toInt();
    description = json['description']?.toString();
    pinkMode = json['pinkMode'];
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    data['price'] = price;
    data['seatAvailable'] = seatAvailable;
    data['description'] = description;
    data['pinkMode'] = pinkMode;
    data['_id'] = Id;
    return data;
  }
}

class MessageListModelChatRoomIdsUser2NotificationPreferences {
/*
{
  "trip": true,
  "alerts": true,
  "payments": true,
  "transactions": true,
  "offers": true
} 
*/

  bool? trip;
  bool? alerts;
  bool? payments;
  bool? transactions;
  bool? offers;

  MessageListModelChatRoomIdsUser2NotificationPreferences({
    this.trip,
    this.alerts,
    this.payments,
    this.transactions,
    this.offers,
  });
  MessageListModelChatRoomIdsUser2NotificationPreferences.fromJson(
      Map<String, dynamic> json) {
    trip = json['trip'];
    alerts = json['alerts'];
    payments = json['payments'];
    transactions = json['transactions'];
    offers = json['offers'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    data['alerts'] = alerts;
    data['payments'] = payments;
    data['transactions'] = transactions;
    data['offers'] = offers;
    return data;
  }
}

class MessageListModelChatRoomIdsUser2RideCancellationDetailsSuspensionDetails {
/*
{
  "cancelPolicy": ""
} 
*/

  String? cancelPolicy;

  MessageListModelChatRoomIdsUser2RideCancellationDetailsSuspensionDetails({
    this.cancelPolicy,
  });
  MessageListModelChatRoomIdsUser2RideCancellationDetailsSuspensionDetails.fromJson(
      Map<String, dynamic> json) {
    cancelPolicy = json['cancelPolicy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cancelPolicy'] = cancelPolicy;
    return data;
  }
}

class MessageListModelChatRoomIdsUser2RideCancellationDetails {
/*
{
  "suspensionDetails": {
    "cancelPolicy": ""
  },
  "count": 0
} 
*/

  MessageListModelChatRoomIdsUser2RideCancellationDetailsSuspensionDetails?
      suspensionDetails;
  int? count;

  MessageListModelChatRoomIdsUser2RideCancellationDetails({
    this.suspensionDetails,
    this.count,
  });
  MessageListModelChatRoomIdsUser2RideCancellationDetails.fromJson(
      Map<String, dynamic> json) {
    suspensionDetails = (json['suspensionDetails'] != null)
        ? MessageListModelChatRoomIdsUser2RideCancellationDetailsSuspensionDetails
            .fromJson(json['suspensionDetails'])
        : null;
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (suspensionDetails != null) {
      data['suspensionDetails'] = suspensionDetails!.toJson();
    }
    data['count'] = count;
    return data;
  }
}

class MessageListModelChatRoomIdsUser2ProfilePic {
/*
{
  "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
} 
*/

  String? key;
  String? url;

  MessageListModelChatRoomIdsUser2ProfilePic({
    this.key,
    this.url,
  });
  MessageListModelChatRoomIdsUser2ProfilePic.fromJson(
      Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class MessageListModelChatRoomIdsUser2 {
/*
{
  "_id": "676008013109b08b4eaec30b",
  "isRegister": true,
  "role": "User",
  "pinkMode": false,
  "fullName": "UserFour",
  "phone": "+14444444444",
  "email": null,
  "city": "108 Mile Ranch, British Columbia",
  "profilePic": {
    "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
  },
  "idPic": null,
  "dob": "22/12/2006",
  "gender": "Female",
  "isDriver": true,
  "referralCode": "B0497Z1796",
  "profileStatus": true,
  "vehicleStatus": true,
  "status": "active",
  "rideCancellationDetails": {
    "suspensionDetails": {
      "cancelPolicy": ""
    },
    "count": 0
  },
  "wallet": 0,
  "connected_account_id": "",
  "rating": 5,
  "totalRides": 0,
  "isRecurringTripEnabled": false,
  "notificationPreferences": {
    "trip": true,
    "alerts": true,
    "payments": true,
    "transactions": true,
    "offers": true
  },
  "firebaseUid": "5CEN4QW13XP5lZ2IwukHdAHxFEF2",
  "firebaseSignInProvider": "phone",
  "stripeAccountId": null,
  "createdAt": "2024-12-16T10:59:13.085Z",
  "updatedAt": "2025-01-27T06:33:31.277Z"
} 
*/

  String? Id;
  bool? isRegister;
  String? role;
  bool? pinkMode;
  String? fullName;
  String? phone;
  String? email;
  String? city;
  MessageListModelChatRoomIdsUser2ProfilePic? profilePic;
  String? idPic;
  String? dob;
  String? gender;
  bool? isDriver;
  String? referralCode;
  bool? profileStatus;
  bool? vehicleStatus;
  String? status;
  MessageListModelChatRoomIdsUser2RideCancellationDetails?
      rideCancellationDetails;
  int? wallet;
  String? connectedAccountId;
  int? rating;
  int? totalRides;
  bool? isRecurringTripEnabled;
  MessageListModelChatRoomIdsUser2NotificationPreferences?
      notificationPreferences;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? stripeAccountId;
  String? createdAt;
  String? updatedAt;

  MessageListModelChatRoomIdsUser2({
    this.Id,
    this.isRegister,
    this.role,
    this.pinkMode,
    this.fullName,
    this.phone,
    this.email,
    this.city,
    this.profilePic,
    this.idPic,
    this.dob,
    this.gender,
    this.isDriver,
    this.referralCode,
    this.profileStatus,
    this.vehicleStatus,
    this.status,
    this.rideCancellationDetails,
    this.wallet,
    this.connectedAccountId,
    this.rating,
    this.totalRides,
    this.isRecurringTripEnabled,
    this.notificationPreferences,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.stripeAccountId,
    this.createdAt,
    this.updatedAt,
  });
  MessageListModelChatRoomIdsUser2.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    isRegister = json['isRegister'];
    role = json['role']?.toString();
    pinkMode = json['pinkMode'];
    fullName = json['fullName']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    city = json['city']?.toString();
    profilePic = (json['profilePic'] != null)
        ? MessageListModelChatRoomIdsUser2ProfilePic.fromJson(
            json['profilePic'])
        : null;
    idPic = json['idPic']?.toString();
    dob = json['dob']?.toString();
    gender = json['gender']?.toString();
    isDriver = json['isDriver'];
    referralCode = json['referralCode']?.toString();
    profileStatus = json['profileStatus'];
    vehicleStatus = json['vehicleStatus'];
    status = json['status']?.toString();
    rideCancellationDetails = (json['rideCancellationDetails'] != null)
        ? MessageListModelChatRoomIdsUser2RideCancellationDetails.fromJson(
            json['rideCancellationDetails'])
        : null;
    wallet = json['wallet']?.toInt();
    connectedAccountId = json['connected_account_id']?.toString();
    rating = json['rating']?.toInt();
    totalRides = json['totalRides']?.toInt();
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
    notificationPreferences = (json['notificationPreferences'] != null)
        ? MessageListModelChatRoomIdsUser2NotificationPreferences.fromJson(
            json['notificationPreferences'])
        : null;
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    stripeAccountId = json['stripeAccountId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['isRegister'] = isRegister;
    data['role'] = role;
    data['pinkMode'] = pinkMode;
    data['fullName'] = fullName;
    data['phone'] = phone;
    data['email'] = email;
    data['city'] = city;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['idPic'] = idPic;
    data['dob'] = dob;
    data['gender'] = gender;
    data['isDriver'] = isDriver;
    data['referralCode'] = referralCode;
    data['profileStatus'] = profileStatus;
    data['vehicleStatus'] = vehicleStatus;
    data['status'] = status;
    if (rideCancellationDetails != null) {
      data['rideCancellationDetails'] = rideCancellationDetails!.toJson();
    }
    data['wallet'] = wallet;
    data['connected_account_id'] = connectedAccountId;
    data['rating'] = rating;
    data['totalRides'] = totalRides;
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    if (notificationPreferences != null) {
      data['notificationPreferences'] = notificationPreferences!.toJson();
    }
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['stripeAccountId'] = stripeAccountId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1NotificationPreferences {
/*
{
  "trip": false,
  "alerts": false,
  "payments": true,
  "transactions": true,
  "offers": true
} 
*/

  bool? trip;
  bool? alerts;
  bool? payments;
  bool? transactions;
  bool? offers;

  MessageListModelChatRoomIdsUser1NotificationPreferences({
    this.trip,
    this.alerts,
    this.payments,
    this.transactions,
    this.offers,
  });
  MessageListModelChatRoomIdsUser1NotificationPreferences.fromJson(
      Map<String, dynamic> json) {
    trip = json['trip'];
    alerts = json['alerts'];
    payments = json['payments'];
    transactions = json['transactions'];
    offers = json['offers'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    data['alerts'] = alerts;
    data['payments'] = payments;
    data['transactions'] = transactions;
    data['offers'] = offers;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1RideCancellationDetailsSuspensionDetails {
/*
{
  "cancelPolicy": ""
} 
*/

  String? cancelPolicy;

  MessageListModelChatRoomIdsUser1RideCancellationDetailsSuspensionDetails({
    this.cancelPolicy,
  });
  MessageListModelChatRoomIdsUser1RideCancellationDetailsSuspensionDetails.fromJson(
      Map<String, dynamic> json) {
    cancelPolicy = json['cancelPolicy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cancelPolicy'] = cancelPolicy;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1RideCancellationDetails {
/*
{
  "suspensionDetails": {
    "cancelPolicy": ""
  },
  "count": 0
} 
*/

  MessageListModelChatRoomIdsUser1RideCancellationDetailsSuspensionDetails?
      suspensionDetails;
  int? count;

  MessageListModelChatRoomIdsUser1RideCancellationDetails({
    this.suspensionDetails,
    this.count,
  });
  MessageListModelChatRoomIdsUser1RideCancellationDetails.fromJson(
      Map<String, dynamic> json) {
    suspensionDetails = (json['suspensionDetails'] != null)
        ? MessageListModelChatRoomIdsUser1RideCancellationDetailsSuspensionDetails
            .fromJson(json['suspensionDetails'])
        : null;
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (suspensionDetails != null) {
      data['suspensionDetails'] = suspensionDetails!.toJson();
    }
    data['count'] = count;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1IdPic {
/*
{
  "key": "idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
  "_id": "677789a3328052ff77d6eae5"
} 
*/

  String? key;
  String? url;
  String? Id;

  MessageListModelChatRoomIdsUser1IdPic({
    this.key,
    this.url,
    this.Id,
  });
  MessageListModelChatRoomIdsUser1IdPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1ProfilePic {
/*
{
  "key": "usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
} 
*/

  String? key;
  String? url;

  MessageListModelChatRoomIdsUser1ProfilePic({
    this.key,
    this.url,
  });
  MessageListModelChatRoomIdsUser1ProfilePic.fromJson(
      Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class MessageListModelChatRoomIdsUser1 {
/*
{
  "_id": "6777895d328052ff77d6eadf",
  "isRegister": true,
  "role": "User",
  "pinkMode": false,
  "fullName": "Alok Sharma",
  "phone": null,
  "email": "aloksharma@ideausher.com",
  "city": "Kitimat, British Columbia",
  "profilePic": {
    "key": "usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
  },
  "idPic": {
    "key": "idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
    "_id": "677789a3328052ff77d6eae5"
  },
  "dob": "2007-01-03",
  "gender": "Select",
  "isDriver": true,
  "referralCode": "E6652V6342",
  "profileStatus": true,
  "vehicleStatus": true,
  "status": "active",
  "rideCancellationDetails": {
    "suspensionDetails": {
      "cancelPolicy": ""
    },
    "count": 0
  },
  "wallet": 0,
  "connected_account_id": "",
  "rating": 0,
  "totalRides": 0,
  "isRecurringTripEnabled": false,
  "notificationPreferences": {
    "trip": false,
    "alerts": false,
    "payments": true,
    "transactions": true,
    "offers": true
  },
  "firebaseUid": "31uGJiQCNAgu1W5C8g57MfSsg3l1",
  "firebaseSignInProvider": "google.com",
  "stripeAccountId": null,
  "createdAt": "2025-01-03T06:53:17.440Z",
  "updatedAt": "2025-01-24T09:39:36.120Z"
} 
*/

  String? Id;
  bool? isRegister;
  String? role;
  bool? pinkMode;
  String? fullName;
  String? phone;
  String? email;
  String? city;
  MessageListModelChatRoomIdsUser1ProfilePic? profilePic;
  MessageListModelChatRoomIdsUser1IdPic? idPic;
  String? dob;
  String? gender;
  bool? isDriver;
  String? referralCode;
  bool? profileStatus;
  bool? vehicleStatus;
  String? status;
  MessageListModelChatRoomIdsUser1RideCancellationDetails?
      rideCancellationDetails;
  int? wallet;
  String? connectedAccountId;
  int? rating;
  int? totalRides;
  bool? isRecurringTripEnabled;
  MessageListModelChatRoomIdsUser1NotificationPreferences?
      notificationPreferences;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? stripeAccountId;
  String? createdAt;
  String? updatedAt;

  MessageListModelChatRoomIdsUser1({
    this.Id,
    this.isRegister,
    this.role,
    this.pinkMode,
    this.fullName,
    this.phone,
    this.email,
    this.city,
    this.profilePic,
    this.idPic,
    this.dob,
    this.gender,
    this.isDriver,
    this.referralCode,
    this.profileStatus,
    this.vehicleStatus,
    this.status,
    this.rideCancellationDetails,
    this.wallet,
    this.connectedAccountId,
    this.rating,
    this.totalRides,
    this.isRecurringTripEnabled,
    this.notificationPreferences,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.stripeAccountId,
    this.createdAt,
    this.updatedAt,
  });
  MessageListModelChatRoomIdsUser1.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    isRegister = json['isRegister'];
    role = json['role']?.toString();
    pinkMode = json['pinkMode'];
    fullName = json['fullName']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    city = json['city']?.toString();
    profilePic = (json['profilePic'] != null)
        ? MessageListModelChatRoomIdsUser1ProfilePic.fromJson(
            json['profilePic'])
        : null;
    idPic = (json['idPic'] != null)
        ? MessageListModelChatRoomIdsUser1IdPic.fromJson(json['idPic'])
        : null;
    dob = json['dob']?.toString();
    gender = json['gender']?.toString();
    isDriver = json['isDriver'];
    referralCode = json['referralCode']?.toString();
    profileStatus = json['profileStatus'];
    vehicleStatus = json['vehicleStatus'];
    status = json['status']?.toString();
    rideCancellationDetails = (json['rideCancellationDetails'] != null)
        ? MessageListModelChatRoomIdsUser1RideCancellationDetails.fromJson(
            json['rideCancellationDetails'])
        : null;
    wallet = json['wallet']?.toInt();
    connectedAccountId = json['connected_account_id']?.toString();
    rating = json['rating']?.toInt();
    totalRides = json['totalRides']?.toInt();
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
    notificationPreferences = (json['notificationPreferences'] != null)
        ? MessageListModelChatRoomIdsUser1NotificationPreferences.fromJson(
            json['notificationPreferences'])
        : null;
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    stripeAccountId = json['stripeAccountId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['isRegister'] = isRegister;
    data['role'] = role;
    data['pinkMode'] = pinkMode;
    data['fullName'] = fullName;
    data['phone'] = phone;
    data['email'] = email;
    data['city'] = city;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    if (idPic != null) {
      data['idPic'] = idPic!.toJson();
    }
    data['dob'] = dob;
    data['gender'] = gender;
    data['isDriver'] = isDriver;
    data['referralCode'] = referralCode;
    data['profileStatus'] = profileStatus;
    data['vehicleStatus'] = vehicleStatus;
    data['status'] = status;
    if (rideCancellationDetails != null) {
      data['rideCancellationDetails'] = rideCancellationDetails!.toJson();
    }
    data['wallet'] = wallet;
    data['connected_account_id'] = connectedAccountId;
    data['rating'] = rating;
    data['totalRides'] = totalRides;
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    if (notificationPreferences != null) {
      data['notificationPreferences'] = notificationPreferences!.toJson();
    }
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['stripeAccountId'] = stripeAccountId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class MessageListModelChatRoomIds {
/*
{
  "_id": "6790829bd0359bf954d67acb",
  "user1": {
    "_id": "6777895d328052ff77d6eadf",
    "isRegister": true,
    "role": "User",
    "pinkMode": false,
    "fullName": "Alok Sharma",
    "phone": null,
    "email": "aloksharma@ideausher.com",
    "city": "Kitimat, British Columbia",
    "profilePic": {
      "key": "usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
    },
    "idPic": {
      "key": "idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
      "_id": "677789a3328052ff77d6eae5"
    },
    "dob": "2007-01-03",
    "gender": "Select",
    "isDriver": true,
    "referralCode": "E6652V6342",
    "profileStatus": true,
    "vehicleStatus": true,
    "status": "active",
    "rideCancellationDetails": {
      "suspensionDetails": {
        "cancelPolicy": ""
      },
      "count": 0
    },
    "wallet": 0,
    "connected_account_id": "",
    "rating": 0,
    "totalRides": 0,
    "isRecurringTripEnabled": false,
    "notificationPreferences": {
      "trip": false,
      "alerts": false,
      "payments": true,
      "transactions": true,
      "offers": true
    },
    "firebaseUid": "31uGJiQCNAgu1W5C8g57MfSsg3l1",
    "firebaseSignInProvider": "google.com",
    "stripeAccountId": null,
    "createdAt": "2025-01-03T06:53:17.440Z",
    "updatedAt": "2025-01-24T09:39:36.120Z"
  },
  "user2": {
    "_id": "676008013109b08b4eaec30b",
    "isRegister": true,
    "role": "User",
    "pinkMode": false,
    "fullName": "UserFour",
    "phone": "+14444444444",
    "email": null,
    "city": "108 Mile Ranch, British Columbia",
    "profilePic": {
      "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
    },
    "idPic": null,
    "dob": "22/12/2006",
    "gender": "Female",
    "isDriver": true,
    "referralCode": "B0497Z1796",
    "profileStatus": true,
    "vehicleStatus": true,
    "status": "active",
    "rideCancellationDetails": {
      "suspensionDetails": {
        "cancelPolicy": ""
      },
      "count": 0
    },
    "wallet": 0,
    "connected_account_id": "",
    "rating": 5,
    "totalRides": 0,
    "isRecurringTripEnabled": false,
    "notificationPreferences": {
      "trip": true,
      "alerts": true,
      "payments": true,
      "transactions": true,
      "offers": true
    },
    "firebaseUid": "5CEN4QW13XP5lZ2IwukHdAHxFEF2",
    "firebaseSignInProvider": "phone",
    "stripeAccountId": null,
    "createdAt": "2024-12-16T10:59:13.085Z",
    "updatedAt": "2025-01-27T06:33:31.277Z"
  },
  "ridePostId": null,
  "chatRoomId": "room_6777895d328052ff77d6eadf_676008013109b08b4eaec30b_1737523867025",
  "paymentStatus": "Inquiry",
  "lastMessage": "hii",
  "driverRideId": "678f7e8a8ae8dc9897a9707c",
  "riderRideId": "67907fd61c2b7d0ae43cc046",
  "ridesDetails": {
    "origin": {
      "name": "London, ON, Canada",
      "coordinates": [
        "-81.2452768"
      ]
    },
    "destination": {
      "name": "Kitchener, ON, Canada",
      "coordinates": [
        "-80.4925337"
      ]
    },
    "date": "2025-01-26T13:00:00.000Z",
    "time": "2025-01-26T13:00:00.000Z",
    "price": 12,
    "seatAvailable": 4,
    "description": "",
    "pinkMode": false,
    "_id": "6790829bd0359bf954d67acc"
  },
  "updatedAt": "2025-01-22T05:38:27.579Z",
  "deleteUpdateTime": "",
  "reciver": {
    "profilePic": {
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
    },
    "_id": "6777895d328052ff77d6eadf",
    "fullName": "Alok Sharma"
  },
  "unReadCount": 1
} 
*/

  String? Id;
  MessageListModelChatRoomIdsUser1? user1;
  MessageListModelChatRoomIdsUser2? user2;
  String? ridePostId;
  String? chatRoomId;
  String? paymentStatus;
  String? lastMessage;
  String? driverRideId;
  String? riderRideId;
  MessageListModelChatRoomIdsRidesDetails? ridesDetails;
  String? updatedAt;
  String? deleteUpdateTime;
  MessageListModelChatRoomIdsReciver? reciver;
  int? unReadCount;

  MessageListModelChatRoomIds({
    this.Id,
    this.user1,
    this.user2,
    this.ridePostId,
    this.chatRoomId,
    this.paymentStatus,
    this.lastMessage,
    this.driverRideId,
    this.riderRideId,
    this.ridesDetails,
    this.updatedAt,
    this.deleteUpdateTime,
    this.reciver,
    this.unReadCount,
  });
  MessageListModelChatRoomIds.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    user1 = (json['user1'] != null)
        ? MessageListModelChatRoomIdsUser1.fromJson(json['user1'])
        : null;
    user2 = (json['user2'] != null)
        ? MessageListModelChatRoomIdsUser2.fromJson(json['user2'])
        : null;
    ridePostId = json['ridePostId']?.toString();
    chatRoomId = json['chatRoomId']?.toString();
    paymentStatus = json['paymentStatus']?.toString();
    lastMessage = json['lastMessage']?.toString();
    driverRideId = json['driverRideId']?.toString();
    riderRideId = json['riderRideId']?.toString();
    ridesDetails = (json['ridesDetails'] != null)
        ? MessageListModelChatRoomIdsRidesDetails.fromJson(json['ridesDetails'])
        : null;
    updatedAt = json['updatedAt']?.toString();
    deleteUpdateTime = json['deleteUpdateTime']?.toString();
    reciver = (json['reciver'] != null)
        ? MessageListModelChatRoomIdsReciver.fromJson(json['reciver'])
        : null;
    unReadCount = json['unReadCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    if (user1 != null) {
      data['user1'] = user1!.toJson();
    }
    if (user2 != null) {
      data['user2'] = user2!.toJson();
    }
    data['ridePostId'] = ridePostId;
    data['chatRoomId'] = chatRoomId;
    data['paymentStatus'] = paymentStatus;
    data['lastMessage'] = lastMessage;
    data['driverRideId'] = driverRideId;
    data['riderRideId'] = riderRideId;
    if (ridesDetails != null) {
      data['ridesDetails'] = ridesDetails!.toJson();
    }
    data['updatedAt'] = updatedAt;
    data['deleteUpdateTime'] = deleteUpdateTime;
    if (reciver != null) {
      data['reciver'] = reciver!.toJson();
    }
    data['unReadCount'] = unReadCount;
    return data;
  }
}

class MessageListModel {
/*
{
  "chatRoomIds": [
    {
      "_id": "6790829bd0359bf954d67acb",
      "user1": {
        "_id": "6777895d328052ff77d6eadf",
        "isRegister": true,
        "role": "User",
        "pinkMode": false,
        "fullName": "Alok Sharma",
        "phone": null,
        "email": "aloksharma@ideausher.com",
        "city": "Kitimat, British Columbia",
        "profilePic": {
          "key": "usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
        },
        "idPic": {
          "key": "idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/59efe2c4-827a-410d-9b50-8639962b6832-bgImage.png",
          "_id": "677789a3328052ff77d6eae5"
        },
        "dob": "2007-01-03",
        "gender": "Select",
        "isDriver": true,
        "referralCode": "E6652V6342",
        "profileStatus": true,
        "vehicleStatus": true,
        "status": "active",
        "rideCancellationDetails": {
          "suspensionDetails": {
            "cancelPolicy": ""
          },
          "count": 0
        },
        "wallet": 0,
        "connected_account_id": "",
        "rating": 0,
        "totalRides": 0,
        "isRecurringTripEnabled": false,
        "notificationPreferences": {
          "trip": false,
          "alerts": false,
          "payments": true,
          "transactions": true,
          "offers": true
        },
        "firebaseUid": "31uGJiQCNAgu1W5C8g57MfSsg3l1",
        "firebaseSignInProvider": "google.com",
        "stripeAccountId": null,
        "createdAt": "2025-01-03T06:53:17.440Z",
        "updatedAt": "2025-01-24T09:39:36.120Z"
      },
      "user2": {
        "_id": "676008013109b08b4eaec30b",
        "isRegister": true,
        "role": "User",
        "pinkMode": false,
        "fullName": "UserFour",
        "phone": "+14444444444",
        "email": null,
        "city": "108 Mile Ranch, British Columbia",
        "profilePic": {
          "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
        },
        "idPic": null,
        "dob": "22/12/2006",
        "gender": "Female",
        "isDriver": true,
        "referralCode": "B0497Z1796",
        "profileStatus": true,
        "vehicleStatus": true,
        "status": "active",
        "rideCancellationDetails": {
          "suspensionDetails": {
            "cancelPolicy": ""
          },
          "count": 0
        },
        "wallet": 0,
        "connected_account_id": "",
        "rating": 5,
        "totalRides": 0,
        "isRecurringTripEnabled": false,
        "notificationPreferences": {
          "trip": true,
          "alerts": true,
          "payments": true,
          "transactions": true,
          "offers": true
        },
        "firebaseUid": "5CEN4QW13XP5lZ2IwukHdAHxFEF2",
        "firebaseSignInProvider": "phone",
        "stripeAccountId": null,
        "createdAt": "2024-12-16T10:59:13.085Z",
        "updatedAt": "2025-01-27T06:33:31.277Z"
      },
      "ridePostId": null,
      "chatRoomId": "room_6777895d328052ff77d6eadf_676008013109b08b4eaec30b_1737523867025",
      "paymentStatus": "Inquiry",
      "lastMessage": "hii",
      "driverRideId": "678f7e8a8ae8dc9897a9707c",
      "riderRideId": "67907fd61c2b7d0ae43cc046",
      "ridesDetails": {
        "origin": {
          "name": "London, ON, Canada",
          "coordinates": [
            "-81.2452768"
          ]
        },
        "destination": {
          "name": "Kitchener, ON, Canada",
          "coordinates": [
            "-80.4925337"
          ]
        },
        "date": "2025-01-26T13:00:00.000Z",
        "time": "2025-01-26T13:00:00.000Z",
        "price": 12,
        "seatAvailable": 4,
        "description": "",
        "pinkMode": false,
        "_id": "6790829bd0359bf954d67acc"
      },
      "updatedAt": "2025-01-22T05:38:27.579Z",
      "deleteUpdateTime": "",
      "reciver": {
        "profilePic": {
          "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/ccab4f11-0eed-4ac5-b658-6ec7a36e25db-bgImage.png"
        },
        "_id": "6777895d328052ff77d6eadf",
        "fullName": "Alok Sharma"
      },
      "unReadCount": 1
    }
  ]
} 
*/

  List<MessageListModelChatRoomIds?>? chatRoomIds;

  MessageListModel({
    this.chatRoomIds,
  });
  MessageListModel.fromJson(Map<String, dynamic> json) {
    if (json['chatRoomIds'] != null) {
      final v = json['chatRoomIds'];
      final arr0 = <MessageListModelChatRoomIds>[];
      v.forEach((v) {
        arr0.add(MessageListModelChatRoomIds.fromJson(v));
      });
      chatRoomIds = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (chatRoomIds != null) {
      final v = chatRoomIds;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['chatRoomIds'] = arr0;
    }
    return data;
  }
}
