///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostRideModelRidesDetailsPreferencesOther {
/*
{
  "AppreciatesConversation": true
} 
*/

  bool? AppreciatesConversation;

  PostRideModelRidesDetailsPreferencesOther({
    this.AppreciatesConversation,
  });
  PostRideModelRidesDetailsPreferencesOther.fromJson(
      Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    return data;
  }
}

class PostRideModelRidesDetailsPreferences {
/*
{
  "seatAvailable": 2,
  "luggageType": "S",
  "other": [
    {
      "AppreciatesConversation": true
    }
  ]
} 
*/

  int? seatAvailable;
  String? luggageType;
  List<PostRideModelRidesDetailsPreferencesOther?>? other;

  PostRideModelRidesDetailsPreferences({
    this.seatAvailable,
    this.luggageType,
    this.other,
  });
  PostRideModelRidesDetailsPreferences.fromJson(Map<String, dynamic> json) {
    seatAvailable = json['seatAvailable']?.toInt();
    luggageType = json['luggageType']?.toString();
    if (json['other'] != null) {
      final v = json['other'];
      final arr0 = <PostRideModelRidesDetailsPreferencesOther>[];
      v.forEach((v) {
        arr0.add(PostRideModelRidesDetailsPreferencesOther.fromJson(v));
      });
      other = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['seatAvailable'] = seatAvailable;
    data['luggageType'] = luggageType;
    if (other != null) {
      final v = other;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['other'] = arr0;
    }
    return data;
  }
}

class PostRideModelRidesDetailsReturnTrip {
/*
{
  "isReturnTrip": true,
  "returnDate": "2024-01-30T07:00:17.320+00:00",
  "returnTime": "11:00AM"
} 
*/

  bool? isReturnTrip;
  String? returnDate;
  String? returnTime;

  PostRideModelRidesDetailsReturnTrip({
    this.isReturnTrip,
    this.returnDate,
    this.returnTime,
  });
  PostRideModelRidesDetailsReturnTrip.fromJson(Map<String, dynamic> json) {
    isReturnTrip = json['isReturnTrip'];
    returnDate = json['returnDate']?.toString();
    returnTime = json['returnTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isReturnTrip'] = isReturnTrip;
    data['returnDate'] = returnDate;
    data['returnTime'] = returnTime;
    return data;
  }
}

class PostRideModelRidesDetailsStops {
/*
{
  "name": "ambala",
  "longitude": 77.3116,
  "latitude": 28.5851
} 
*/

  String? name;
  double? longitude;
  double? latitude;

  PostRideModelRidesDetailsStops({
    this.name,
    this.longitude,
    this.latitude,
  });
  PostRideModelRidesDetailsStops.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class PostRideModelRidesDetailsDestination {
/*
{
  "name": "punjab",
  "longitude": 77.323107,
  "latitude": 28.569578
} 
*/

  String? name;
  double? longitude;
  double? latitude;

  PostRideModelRidesDetailsDestination({
    this.name,
    this.longitude,
    this.latitude,
  });
  PostRideModelRidesDetailsDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class PostRideModelRidesDetailsOrigin {
/*
{
  "name": "Delhi",
  "longitude": 77.310181,
  "latitude": 28.582783
} 
*/

  String? name;
  double? longitude;
  double? latitude;

  PostRideModelRidesDetailsOrigin({
    this.name,
    this.longitude,
    this.latitude,
  });
  PostRideModelRidesDetailsOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class PostRideModelRidesDetails {
/*
{
  "origin": {
    "name": "Delhi",
    "longitude": 77.310181,
    "latitude": 28.582783
  },
  "destination": {
    "name": "punjab",
    "longitude": 77.323107,
    "latitude": 28.569578
  },
  "stops": [
    {
      "name": "ambala",
      "longitude": 77.3116,
      "latitude": 28.5851
    }
  ],
  "tripType": "oneTime",
  "date": "2024-01-29T07:00:17.320+00:00",
  "time": "11:00 AM",
  "returnTrip": {
    "isReturnTrip": true,
    "returnDate": "2024-01-30T07:00:17.320+00:00",
    "returnTime": "11:00AM"
  },
  "fair": 12,
  "preferences": {
    "seatAvailable": 2,
    "luggageType": "S",
    "other": [
      {
        "AppreciatesConversation": true
      }
    ]
  }
} 
*/

  PostRideModelRidesDetailsOrigin? origin;
  PostRideModelRidesDetailsDestination? destination;
  List<PostRideModelRidesDetailsStops?>? stops;
  String? tripType;
  String? date;
  String? time;
  PostRideModelRidesDetailsReturnTrip? returnTrip;
  int? fair;
  PostRideModelRidesDetailsPreferences? preferences;

  PostRideModelRidesDetails({
    this.origin,
    this.destination,
    this.stops,
    this.tripType,
    this.date,
    this.time,
    this.returnTrip,
    this.fair,
    this.preferences,
  });
  PostRideModelRidesDetails.fromJson(Map<String, dynamic> json) {
    origin = (json['origin'] != null)
        ? PostRideModelRidesDetailsOrigin.fromJson(json['origin'])
        : null;
    destination = (json['destination'] != null)
        ? PostRideModelRidesDetailsDestination.fromJson(json['destination'])
        : null;
    if (json['stops'] != null) {
      final v = json['stops'];
      final arr0 = <PostRideModelRidesDetailsStops>[];
      v.forEach((v) {
        arr0.add(PostRideModelRidesDetailsStops.fromJson(v));
      });
      stops = arr0;
    }
    tripType = json['tripType']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
    returnTrip = (json['returnTrip'] != null)
        ? PostRideModelRidesDetailsReturnTrip.fromJson(json['returnTrip'])
        : null;
    fair = json['fair']?.toInt();
    preferences = (json['preferences'] != null)
        ? PostRideModelRidesDetailsPreferences.fromJson(json['preferences'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (stops != null) {
      final v = stops;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['stops'] = arr0;
    }
    data['tripType'] = tripType;
    data['date'] = date;
    data['time'] = time;
    if (returnTrip != null) {
      data['returnTrip'] = returnTrip!.toJson();
    }
    data['fair'] = fair;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    return data;
  }
}

class PostRideModel {
/*
{
  "ridesDetails": {
    "origin": {
      "name": "Delhi",
      "longitude": 77.310181,
      "latitude": 28.582783
    },
    "destination": {
      "name": "punjab",
      "longitude": 77.323107,
      "latitude": 28.569578
    },
    "stops": [
      {
        "name": "ambala",
        "longitude": 77.3116,
        "latitude": 28.5851
      }
    ],
    "tripType": "oneTime",
    "date": "2024-01-29T07:00:17.320+00:00",
    "time": "11:00 AM",
    "returnTrip": {
      "isReturnTrip": true,
      "returnDate": "2024-01-30T07:00:17.320+00:00",
      "returnTime": "11:00AM"
    },
    "fair": 12,
    "preferences": {
      "seatAvailable": 2,
      "luggageType": "S",
      "other": [
        {
          "AppreciatesConversation": true
        }
      ]
    }
  }
} 
*/

  PostRideModelRidesDetails? ridesDetails;

  PostRideModel({
    this.ridesDetails,
  });
  PostRideModel.fromJson(Map<String, dynamic> json) {
    ridesDetails = (json['ridesDetails'] != null)
        ? PostRideModelRidesDetails.fromJson(json['ridesDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ridesDetails != null) {
      data['ridesDetails'] = ridesDetails!.toJson();
    }
    return data;
  }
}
