///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RecurringRidesModelDataRidesDetailsRidersDetailsNotificationPreferences {
/*
{
  "trip": true,
  "alerts": true,
  "payments": true,
  "transactions": true,
  "offers": true
} 
*/

  bool? trip;
  bool? alerts;
  bool? payments;
  bool? transactions;
  bool? offers;

  RecurringRidesModelDataRidesDetailsRidersDetailsNotificationPreferences({
    this.trip,
    this.alerts,
    this.payments,
    this.transactions,
    this.offers,
  });
  RecurringRidesModelDataRidesDetailsRidersDetailsNotificationPreferences.fromJson(Map<String, dynamic> json) {
    trip = json['trip'];
    alerts = json['alerts'];
    payments = json['payments'];
    transactions = json['transactions'];
    offers = json['offers'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip'] = trip;
    data['alerts'] = alerts;
    data['payments'] = payments;
    data['transactions'] = transactions;
    data['offers'] = offers;
    return data;
  }
}

class RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetailsSuspensionDetails {
/*
{
  "cancelPolicy": "Driver Cancellation policy",
  "dateFrom": "2024-07-27T11:43:07.435Z",
  "dateTo": "2025-01-27T11:43:07.435Z"
} 
*/

  String? cancelPolicy;
  String? dateFrom;
  String? dateTo;

  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetailsSuspensionDetails({
    this.cancelPolicy,
    this.dateFrom,
    this.dateTo,
  });
  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetailsSuspensionDetails.fromJson(Map<String, dynamic> json) {
    cancelPolicy = json['cancelPolicy']?.toString();
    dateFrom = json['dateFrom']?.toString();
    dateTo = json['dateTo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cancelPolicy'] = cancelPolicy;
    data['dateFrom'] = dateFrom;
    data['dateTo'] = dateTo;
    return data;
  }
}

class RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetails {
/*
{
  "count": 2,
  "cancellationDate": "2024-07-27T11:43:07.435Z",
  "suspensionDetails": {
    "cancelPolicy": "Driver Cancellation policy",
    "dateFrom": "2024-07-27T11:43:07.435Z",
    "dateTo": "2025-01-27T11:43:07.435Z"
  }
} 
*/

  int? count;
  String? cancellationDate;
  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetailsSuspensionDetails? suspensionDetails;

  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetails({
    this.count,
    this.cancellationDate,
    this.suspensionDetails,
  });
  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetails.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
    cancellationDate = json['cancellationDate']?.toString();
    suspensionDetails = (json['suspensionDetails'] != null) ? RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetailsSuspensionDetails.fromJson(json['suspensionDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    data['cancellationDate'] = cancellationDate;
    if (suspensionDetails != null) {
      data['suspensionDetails'] = suspensionDetails!.toJson();
    }
    return data;
  }
}

class RecurringRidesModelDataRidesDetailsRidersDetailsIdPic {
/*
{
  "key": "idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
  "_id": "66a32e4df75f826da1b6d1ea"
} 
*/

  String? key;
  String? url;
  String? Id;

  RecurringRidesModelDataRidesDetailsRidersDetailsIdPic({
    this.key,
    this.url,
    this.Id,
  });
  RecurringRidesModelDataRidesDetailsRidersDetailsIdPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class RecurringRidesModelDataRidesDetailsRidersDetailsProfilePic {
/*
{
  "key": "usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg"
} 
*/

  String? key;
  String? url;

  RecurringRidesModelDataRidesDetailsRidersDetailsProfilePic({
    this.key,
    this.url,
  });
  RecurringRidesModelDataRidesDetailsRidersDetailsProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class RecurringRidesModelDataRidesDetailsRidersDetails {
/*
{
  "_id": "66a24c9cccdad87a58c6428d",
  "isRegister": true,
  "role": "User",
  "pinkMode": false,
  "fullName": "Jaspreet",
  "phone": "+14444444444",
  "email": null,
  "city": "Hisar",
  "profilePic": {
    "key": "usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg"
  },
  "idPic": {
    "key": "idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
    "_id": "66a32e4df75f826da1b6d1ea"
  },
  "dob": "2024-07-25",
  "gender": "Female",
  "isDriver": true,
  "referralCode": "L8555A1312",
  "profileStatus": true,
  "vehicleStatus": true,
  "status": "suspended",
  "rideCancellationDetails": {
    "count": 2,
    "cancellationDate": "2024-07-27T11:43:07.435Z",
    "suspensionDetails": {
      "cancelPolicy": "Driver Cancellation policy",
      "dateFrom": "2024-07-27T11:43:07.435Z",
      "dateTo": "2025-01-27T11:43:07.435Z"
    }
  },
  "wallet": 0,
  "connected_account_id": "acct_1Pl862SDQsFXeYIV",
  "rating": 0,
  "totalRides": 0,
  "isRecurringTripEnabled": false,
  "notificationPreferences": {
    "trip": true,
    "alerts": true,
    "payments": true,
    "transactions": true,
    "offers": true
  },
  "firebaseUid": "ZQ5rkqoYWLV5AUctnbkcvu1Z2hb2",
  "firebaseSignInProvider": "phone",
  "createdAt": "2024-07-25T13:01:16.092Z",
  "updatedAt": "2024-08-10T08:30:14.430Z"
} 
*/

  String? Id;
  bool? isRegister;
  String? role;
  bool? pinkMode;
  String? fullName;
  String? phone;
  String? email;
  String? city;
  RecurringRidesModelDataRidesDetailsRidersDetailsProfilePic? profilePic;
  RecurringRidesModelDataRidesDetailsRidersDetailsIdPic? idPic;
  String? dob;
  String? gender;
  bool? isDriver;
  String? referralCode;
  bool? profileStatus;
  bool? vehicleStatus;
  String? status;
  RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetails? rideCancellationDetails;
  int? wallet;
  String? connectedAccountId;
  int? rating;
  int? totalRides;
  bool? isRecurringTripEnabled;
  RecurringRidesModelDataRidesDetailsRidersDetailsNotificationPreferences? notificationPreferences;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? createdAt;
  String? updatedAt;

  RecurringRidesModelDataRidesDetailsRidersDetails({
    this.Id,
    this.isRegister,
    this.role,
    this.pinkMode,
    this.fullName,
    this.phone,
    this.email,
    this.city,
    this.profilePic,
    this.idPic,
    this.dob,
    this.gender,
    this.isDriver,
    this.referralCode,
    this.profileStatus,
    this.vehicleStatus,
    this.status,
    this.rideCancellationDetails,
    this.wallet,
    this.connectedAccountId,
    this.rating,
    this.totalRides,
    this.isRecurringTripEnabled,
    this.notificationPreferences,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.createdAt,
    this.updatedAt,
  });
  RecurringRidesModelDataRidesDetailsRidersDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    isRegister = json['isRegister'];
    role = json['role']?.toString();
    pinkMode = json['pinkMode'];
    fullName = json['fullName']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    city = json['city']?.toString();
    profilePic = (json['profilePic'] != null) ? RecurringRidesModelDataRidesDetailsRidersDetailsProfilePic.fromJson(json['profilePic']) : null;
    idPic = (json['idPic'] != null) ? RecurringRidesModelDataRidesDetailsRidersDetailsIdPic.fromJson(json['idPic']) : null;
    dob = json['dob']?.toString();
    gender = json['gender']?.toString();
    isDriver = json['isDriver'];
    referralCode = json['referralCode']?.toString();
    profileStatus = json['profileStatus'];
    vehicleStatus = json['vehicleStatus'];
    status = json['status']?.toString();
    rideCancellationDetails = (json['rideCancellationDetails'] != null) ? RecurringRidesModelDataRidesDetailsRidersDetailsRideCancellationDetails.fromJson(json['rideCancellationDetails']) : null;
    wallet = json['wallet']?.toInt();
    connectedAccountId = json['connected_account_id']?.toString();
    rating = json['rating']?.toInt();
    totalRides = json['totalRides']?.toInt();
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
    notificationPreferences = (json['notificationPreferences'] != null) ? RecurringRidesModelDataRidesDetailsRidersDetailsNotificationPreferences.fromJson(json['notificationPreferences']) : null;
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['isRegister'] = isRegister;
    data['role'] = role;
    data['pinkMode'] = pinkMode;
    data['fullName'] = fullName;
    data['phone'] = phone;
    data['email'] = email;
    data['city'] = city;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    if (idPic != null) {
      data['idPic'] = idPic!.toJson();
    }
    data['dob'] = dob;
    data['gender'] = gender;
    data['isDriver'] = isDriver;
    data['referralCode'] = referralCode;
    data['profileStatus'] = profileStatus;
    data['vehicleStatus'] = vehicleStatus;
    data['status'] = status;
    if (rideCancellationDetails != null) {
      data['rideCancellationDetails'] = rideCancellationDetails!.toJson();
    }
    data['wallet'] = wallet;
    data['connected_account_id'] = connectedAccountId;
    data['rating'] = rating;
    data['totalRides'] = totalRides;
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    if (notificationPreferences != null) {
      data['notificationPreferences'] = notificationPreferences!.toJson();
    }
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class RecurringRidesModelDataRidesDetails {
/*
{
  "date": "2024-08-11T00:00:00.000Z",
  "dayOfWeek": 1,
  "day": "Sunday",
  "totalSeatAvailable": 4,
  "seatAvailable": 4,
  "ridersDetails": [
    {
      "_id": "66a24c9cccdad87a58c6428d",
      "isRegister": true,
      "role": "User",
      "pinkMode": false,
      "fullName": "Jaspreet",
      "phone": "+14444444444",
      "email": null,
      "city": "Hisar",
      "profilePic": {
        "key": "usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg"
      },
      "idPic": {
        "key": "idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
        "_id": "66a32e4df75f826da1b6d1ea"
      },
      "dob": "2024-07-25",
      "gender": "Female",
      "isDriver": true,
      "referralCode": "L8555A1312",
      "profileStatus": true,
      "vehicleStatus": true,
      "status": "suspended",
      "rideCancellationDetails": {
        "count": 2,
        "cancellationDate": "2024-07-27T11:43:07.435Z",
        "suspensionDetails": {
          "cancelPolicy": "Driver Cancellation policy",
          "dateFrom": "2024-07-27T11:43:07.435Z",
          "dateTo": "2025-01-27T11:43:07.435Z"
        }
      },
      "wallet": 0,
      "connected_account_id": "acct_1Pl862SDQsFXeYIV",
      "rating": 0,
      "totalRides": 0,
      "isRecurringTripEnabled": false,
      "notificationPreferences": {
        "trip": true,
        "alerts": true,
        "payments": true,
        "transactions": true,
        "offers": true
      },
      "firebaseUid": "ZQ5rkqoYWLV5AUctnbkcvu1Z2hb2",
      "firebaseSignInProvider": "phone",
      "createdAt": "2024-07-25T13:01:16.092Z",
      "updatedAt": "2024-08-10T08:30:14.430Z"
    }
  ]
} 
*/

  String? date;
  int? dayOfWeek;
  String? day;
  int? totalSeatAvailable;
  int? seatAvailable;
  List<RecurringRidesModelDataRidesDetailsRidersDetails?>? ridersDetails;

  RecurringRidesModelDataRidesDetails({
    this.date,
    this.dayOfWeek,
    this.day,
    this.totalSeatAvailable,
    this.seatAvailable,
    this.ridersDetails,
  });
  RecurringRidesModelDataRidesDetails.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    dayOfWeek = json['dayOfWeek']?.toInt();
    day = json['day']?.toString();
    totalSeatAvailable = json['totalSeatAvailable']?.toInt();
    seatAvailable = json['seatAvailable']?.toInt();
  if (json['ridersDetails'] != null) {
  final v = json['ridersDetails'];
  final arr0 = <RecurringRidesModelDataRidesDetailsRidersDetails>[];
  v.forEach((v) {
  arr0.add(RecurringRidesModelDataRidesDetailsRidersDetails.fromJson(v));
  });
    ridersDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['dayOfWeek'] = dayOfWeek;
    data['day'] = day;
    data['totalSeatAvailable'] = totalSeatAvailable;
    data['seatAvailable'] = seatAvailable;
    if (ridersDetails != null) {
      final v = ridersDetails;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['ridersDetails'] = arr0;
    }
    return data;
  }
}

class RecurringRidesModelDataPreferencesOther {
/*
{
  "AppreciatesConversation": true,
  "EnjoysMusic": false,
  "SmokeFree": false,
  "PetFriendly": false,
  "WinterTires": false,
  "CoolingOrHeating": false,
  "BabySeat": false,
  "HeatedSeats": false
} 
*/

  bool? AppreciatesConversation;
  bool? EnjoysMusic;
  bool? SmokeFree;
  bool? PetFriendly;
  bool? WinterTires;
  bool? CoolingOrHeating;
  bool? BabySeat;
  bool? HeatedSeats;

  RecurringRidesModelDataPreferencesOther({
    this.AppreciatesConversation,
    this.EnjoysMusic,
    this.SmokeFree,
    this.PetFriendly,
    this.WinterTires,
    this.CoolingOrHeating,
    this.BabySeat,
    this.HeatedSeats,
  });
  RecurringRidesModelDataPreferencesOther.fromJson(Map<String, dynamic> json) {
    AppreciatesConversation = json['AppreciatesConversation'];
    EnjoysMusic = json['EnjoysMusic'];
    SmokeFree = json['SmokeFree'];
    PetFriendly = json['PetFriendly'];
    WinterTires = json['WinterTires'];
    CoolingOrHeating = json['CoolingOrHeating'];
    BabySeat = json['BabySeat'];
    HeatedSeats = json['HeatedSeats'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AppreciatesConversation'] = AppreciatesConversation;
    data['EnjoysMusic'] = EnjoysMusic;
    data['SmokeFree'] = SmokeFree;
    data['PetFriendly'] = PetFriendly;
    data['WinterTires'] = WinterTires;
    data['CoolingOrHeating'] = CoolingOrHeating;
    data['BabySeat'] = BabySeat;
    data['HeatedSeats'] = HeatedSeats;
    return data;
  }
}

class RecurringRidesModelDataPreferences {
/*
{
  "luggageType": "S",
  "other": {
    "AppreciatesConversation": true,
    "EnjoysMusic": false,
    "SmokeFree": false,
    "PetFriendly": false,
    "WinterTires": false,
    "CoolingOrHeating": false,
    "BabySeat": false,
    "HeatedSeats": false
  }
} 
*/

  String? luggageType;
  RecurringRidesModelDataPreferencesOther? other;

  RecurringRidesModelDataPreferences({
    this.luggageType,
    this.other,
  });
  RecurringRidesModelDataPreferences.fromJson(Map<String, dynamic> json) {
    luggageType = json['luggageType']?.toString();
    other = (json['other'] != null) ? RecurringRidesModelDataPreferencesOther.fromJson(json['other']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['luggageType'] = luggageType;
    if (other != null) {
      data['other'] = other!.toJson();
    }
    return data;
  }
}

class RecurringRidesModelDataRecurringTrip {
/*
{
  "isRecurringTripEnabled": true
} 
*/

  bool? isRecurringTripEnabled;

  RecurringRidesModelDataRecurringTrip({
    this.isRecurringTripEnabled,
  });
  RecurringRidesModelDataRecurringTrip.fromJson(Map<String, dynamic> json) {
    isRecurringTripEnabled = json['isRecurringTripEnabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isRecurringTripEnabled'] = isRecurringTripEnabled;
    return data;
  }
}

class RecurringRidesModelDataDestination {
/*
{
  "name": "Oakville, ON, Canada",
  "type": "Point",
  "coordinates": [
    -79.6876659
  ]
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;

  RecurringRidesModelDataDestination({
    this.name,
    this.type,
    this.coordinates,
  });
  RecurringRidesModelDataDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class RecurringRidesModelDataOrigin {
/*
{
  "name": "Brampton, ON, Canada",
  "type": "Point",
  "coordinates": [
    -79.7624177
  ],
  "originDestinationFair": "13",
  "time": ""
} 
*/

  String? name;
  String? type;
  List<double?>? coordinates;
  String? originDestinationFair;
  String? time;

  RecurringRidesModelDataOrigin({
    this.name,
    this.type,
    this.coordinates,
    this.originDestinationFair,
    this.time,
  });
  RecurringRidesModelDataOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
    originDestinationFair = json['originDestinationFair']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    data['originDestinationFair'] = originDestinationFair;
    data['time'] = time;
    return data;
  }
}

class RecurringRidesModelData {
/*
{
  "_id": "66b724528bcd6f2d8787f96e",
  "origin": {
    "name": "Brampton, ON, Canada",
    "type": "Point",
    "coordinates": [
      -79.7624177
    ],
    "originDestinationFair": "13",
    "time": ""
  },
  "destination": {
    "name": "Oakville, ON, Canada",
    "type": "Point",
    "coordinates": [
      -79.6876659
    ]
  },
  "recurringTrip": {
    "isRecurringTripEnabled": true
  },
  "date": "2024-08-10T00:00:00.000Z",
  "time": "2024-08-10T10:00:00.000Z",
  "preferences": {
    "luggageType": "S",
    "other": {
      "AppreciatesConversation": true,
      "EnjoysMusic": false,
      "SmokeFree": false,
      "PetFriendly": false,
      "WinterTires": false,
      "CoolingOrHeating": false,
      "BabySeat": false,
      "HeatedSeats": false
    }
  },
  "description": "test ride",
  "ridesDetails": [
    {
      "date": "2024-08-11T00:00:00.000Z",
      "dayOfWeek": 1,
      "day": "Sunday",
      "totalSeatAvailable": 4,
      "seatAvailable": 4,
      "ridersDetails": [
        {
          "_id": "66a24c9cccdad87a58c6428d",
          "isRegister": true,
          "role": "User",
          "pinkMode": false,
          "fullName": "Jaspreet",
          "phone": "+14444444444",
          "email": null,
          "city": "Hisar",
          "profilePic": {
            "key": "usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg"
          },
          "idPic": {
            "key": "idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
            "_id": "66a32e4df75f826da1b6d1ea"
          },
          "dob": "2024-07-25",
          "gender": "Female",
          "isDriver": true,
          "referralCode": "L8555A1312",
          "profileStatus": true,
          "vehicleStatus": true,
          "status": "suspended",
          "rideCancellationDetails": {
            "count": 2,
            "cancellationDate": "2024-07-27T11:43:07.435Z",
            "suspensionDetails": {
              "cancelPolicy": "Driver Cancellation policy",
              "dateFrom": "2024-07-27T11:43:07.435Z",
              "dateTo": "2025-01-27T11:43:07.435Z"
            }
          },
          "wallet": 0,
          "connected_account_id": "acct_1Pl862SDQsFXeYIV",
          "rating": 0,
          "totalRides": 0,
          "isRecurringTripEnabled": false,
          "notificationPreferences": {
            "trip": true,
            "alerts": true,
            "payments": true,
            "transactions": true,
            "offers": true
          },
          "firebaseUid": "ZQ5rkqoYWLV5AUctnbkcvu1Z2hb2",
          "firebaseSignInProvider": "phone",
          "createdAt": "2024-07-25T13:01:16.092Z",
          "updatedAt": "2024-08-10T08:30:14.430Z"
        }
      ]
    }
  ]
} 
*/

  String? Id;
  RecurringRidesModelDataOrigin? origin;
  RecurringRidesModelDataDestination? destination;
  RecurringRidesModelDataRecurringTrip? recurringTrip;
  String? date;
  String? time;
  RecurringRidesModelDataPreferences? preferences;
  String? description;
  List<RecurringRidesModelDataRidesDetails?>? ridesDetails;

  RecurringRidesModelData({
    this.Id,
    this.origin,
    this.destination,
    this.recurringTrip,
    this.date,
    this.time,
    this.preferences,
    this.description,
    this.ridesDetails,
  });
  RecurringRidesModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    origin = (json['origin'] != null) ? RecurringRidesModelDataOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? RecurringRidesModelDataDestination.fromJson(json['destination']) : null;
    recurringTrip = (json['recurringTrip'] != null) ? RecurringRidesModelDataRecurringTrip.fromJson(json['recurringTrip']) : null;
    date = json['date']?.toString();
    time = json['time']?.toString();
    preferences = (json['preferences'] != null) ? RecurringRidesModelDataPreferences.fromJson(json['preferences']) : null;
    description = json['description']?.toString();
  if (json['ridesDetails'] != null) {
  final v = json['ridesDetails'];
  final arr0 = <RecurringRidesModelDataRidesDetails>[];
  v.forEach((v) {
  arr0.add(RecurringRidesModelDataRidesDetails.fromJson(v));
  });
    ridesDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (recurringTrip != null) {
      data['recurringTrip'] = recurringTrip!.toJson();
    }
    data['date'] = date;
    data['time'] = time;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['description'] = description;
    if (ridesDetails != null) {
      final v = ridesDetails;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['ridesDetails'] = arr0;
    }
    return data;
  }
}

class RecurringRidesModel {
/*
{
  "status": true,
  "data": [
    {
      "_id": "66b724528bcd6f2d8787f96e",
      "origin": {
        "name": "Brampton, ON, Canada",
        "type": "Point",
        "coordinates": [
          -79.7624177
        ],
        "originDestinationFair": "13",
        "time": ""
      },
      "destination": {
        "name": "Oakville, ON, Canada",
        "type": "Point",
        "coordinates": [
          -79.6876659
        ]
      },
      "recurringTrip": {
        "isRecurringTripEnabled": true
      },
      "date": "2024-08-10T00:00:00.000Z",
      "time": "2024-08-10T10:00:00.000Z",
      "preferences": {
        "luggageType": "S",
        "other": {
          "AppreciatesConversation": true,
          "EnjoysMusic": false,
          "SmokeFree": false,
          "PetFriendly": false,
          "WinterTires": false,
          "CoolingOrHeating": false,
          "BabySeat": false,
          "HeatedSeats": false
        }
      },
      "description": "test ride",
      "ridesDetails": [
        {
          "date": "2024-08-11T00:00:00.000Z",
          "dayOfWeek": 1,
          "day": "Sunday",
          "totalSeatAvailable": 4,
          "seatAvailable": 4,
          "ridersDetails": [
            {
              "_id": "66a24c9cccdad87a58c6428d",
              "isRegister": true,
              "role": "User",
              "pinkMode": false,
              "fullName": "Jaspreet",
              "phone": "+14444444444",
              "email": null,
              "city": "Hisar",
              "profilePic": {
                "key": "usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg",
                "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/0f143420-9e14-404b-8113-a703b646065f-Gurpreet.jpg"
              },
              "idPic": {
                "key": "idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
                "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/idPic/11e6324a-1e74-409c-a220-806dd0581226-Gurpreet.jpg",
                "_id": "66a32e4df75f826da1b6d1ea"
              },
              "dob": "2024-07-25",
              "gender": "Female",
              "isDriver": true,
              "referralCode": "L8555A1312",
              "profileStatus": true,
              "vehicleStatus": true,
              "status": "suspended",
              "rideCancellationDetails": {
                "count": 2,
                "cancellationDate": "2024-07-27T11:43:07.435Z",
                "suspensionDetails": {
                  "cancelPolicy": "Driver Cancellation policy",
                  "dateFrom": "2024-07-27T11:43:07.435Z",
                  "dateTo": "2025-01-27T11:43:07.435Z"
                }
              },
              "wallet": 0,
              "connected_account_id": "acct_1Pl862SDQsFXeYIV",
              "rating": 0,
              "totalRides": 0,
              "isRecurringTripEnabled": false,
              "notificationPreferences": {
                "trip": true,
                "alerts": true,
                "payments": true,
                "transactions": true,
                "offers": true
              },
              "firebaseUid": "ZQ5rkqoYWLV5AUctnbkcvu1Z2hb2",
              "firebaseSignInProvider": "phone",
              "createdAt": "2024-07-25T13:01:16.092Z",
              "updatedAt": "2024-08-10T08:30:14.430Z"
            }
          ]
        }
      ]
    }
  ],
  "message": "success"
} 
*/

  bool? status;
  List<RecurringRidesModelData?>? data;
  String? message;

  RecurringRidesModel({
    this.status,
    this.data,
    this.message,
  });
  RecurringRidesModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <RecurringRidesModelData>[];
  v.forEach((v) {
  arr0.add(RecurringRidesModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
