///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TransactionsModelDataTransactionsRideDetailsOtherPartyProfilePic {
/*
{
  "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
  "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
} 
*/

  String? key;
  String? url;

  TransactionsModelDataTransactionsRideDetailsOtherPartyProfilePic({
    this.key,
    this.url,
  });
  TransactionsModelDataTransactionsRideDetailsOtherPartyProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class TransactionsModelDataTransactionsRideDetailsOtherParty {
/*
{
  "id": "676008013109b08b4eaec30b",
  "name": "UserFour",
  "profilePic": {
    "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
    "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
  },
  "role": "Rider"
} 
*/

  String? id;
  String? name;
  TransactionsModelDataTransactionsRideDetailsOtherPartyProfilePic? profilePic;
  String? role;

  TransactionsModelDataTransactionsRideDetailsOtherParty({
    this.id,
    this.name,
    this.profilePic,
    this.role,
  });
  TransactionsModelDataTransactionsRideDetailsOtherParty.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    profilePic = (json['profilePic'] != null) ? TransactionsModelDataTransactionsRideDetailsOtherPartyProfilePic.fromJson(json['profilePic']) : null;
    role = json['role']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['role'] = role;
    return data;
  }
}

class TransactionsModelDataTransactionsRideDetailsDestination {
/*
{
  "name": "Brampton, ON, Canada",
  "coordinates": [
    -79.7624177
  ]
} 
*/

  String? name;
  List<double?>? coordinates;

  TransactionsModelDataTransactionsRideDetailsDestination({
    this.name,
    this.coordinates,
  });
  TransactionsModelDataTransactionsRideDetailsDestination.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class TransactionsModelDataTransactionsRideDetailsOrigin {
/*
{
  "name": "Toronto, ON, Canada",
  "coordinates": [
    -79.3831843
  ]
} 
*/

  String? name;
  List<double?>? coordinates;

  TransactionsModelDataTransactionsRideDetailsOrigin({
    this.name,
    this.coordinates,
  });
  TransactionsModelDataTransactionsRideDetailsOrigin.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
  if (json['coordinates'] != null) {
  final v = json['coordinates'];
  final arr0 = <double>[];
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class TransactionsModelDataTransactionsRideDetails {
/*
{
  "origin": {
    "name": "Toronto, ON, Canada",
    "coordinates": [
      -79.3831843
    ]
  },
  "destination": {
    "name": "Brampton, ON, Canada",
    "coordinates": [
      -79.7624177
    ]
  },
  "time": "2025-03-26T08:51:00.000Z",
  "date": "2025-03-26T00:00:00.000Z",
  "status": "",
  "otherParty": {
    "id": "676008013109b08b4eaec30b",
    "name": "UserFour",
    "profilePic": {
      "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
      "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
    },
    "role": "Rider"
  }
} 
*/

  TransactionsModelDataTransactionsRideDetailsOrigin? origin;
  TransactionsModelDataTransactionsRideDetailsDestination? destination;
  String? time;
  String? date;
  String? status;
  TransactionsModelDataTransactionsRideDetailsOtherParty? otherParty;

  TransactionsModelDataTransactionsRideDetails({
    this.origin,
    this.destination,
    this.time,
    this.date,
    this.status,
    this.otherParty,
  });
  TransactionsModelDataTransactionsRideDetails.fromJson(Map<String, dynamic> json) {
    origin = (json['origin'] != null) ? TransactionsModelDataTransactionsRideDetailsOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? TransactionsModelDataTransactionsRideDetailsDestination.fromJson(json['destination']) : null;
    time = json['time']?.toString();
    date = json['date']?.toString();
    status = json['status']?.toString();
    otherParty = (json['otherParty'] != null) ? TransactionsModelDataTransactionsRideDetailsOtherParty.fromJson(json['otherParty']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    data['time'] = time;
    data['date'] = date;
    data['status'] = status;
    if (otherParty != null) {
      data['otherParty'] = otherParty!.toJson();
    }
    return data;
  }
}

class TransactionsModelDataTransactions {
/*
{
  "transactionId": "67e3bfad49bd87e7c20b7dab",
  "type": "ride",
  "userType": "Driver",
  "transactionType": "Credit",
  "amount": 12,
  "date": "2025-03-26T08:49:49.404Z",
  "description": "Amount added to wallet",
  "rideDetails": {
    "origin": {
      "name": "Toronto, ON, Canada",
      "coordinates": [
        -79.3831843
      ]
    },
    "destination": {
      "name": "Brampton, ON, Canada",
      "coordinates": [
        -79.7624177
      ]
    },
    "time": "2025-03-26T08:51:00.000Z",
    "date": "2025-03-26T00:00:00.000Z",
    "status": "",
    "otherParty": {
      "id": "676008013109b08b4eaec30b",
      "name": "UserFour",
      "profilePic": {
        "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
        "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
      },
      "role": "Rider"
    }
  }
} 
*/

  String? transactionId;
  String? type;
  String? userType;
  String? transactionType;
  int? amount;
  String? date;
  String? description;
  TransactionsModelDataTransactionsRideDetails? rideDetails;

  TransactionsModelDataTransactions({
    this.transactionId,
    this.type,
    this.userType,
    this.transactionType,
    this.amount,
    this.date,
    this.description,
    this.rideDetails,
  });
  TransactionsModelDataTransactions.fromJson(Map<String, dynamic> json) {
    transactionId = json['transactionId']?.toString();
    type = json['type']?.toString();
    userType = json['userType']?.toString();
    transactionType = json['transactionType']?.toString();
    amount = json['amount']?.toInt();
    date = json['date']?.toString();
    description = json['description']?.toString();
    rideDetails = (json['rideDetails'] != null) ? TransactionsModelDataTransactionsRideDetails.fromJson(json['rideDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['transactionId'] = transactionId;
    data['type'] = type;
    data['userType'] = userType;
    data['transactionType'] = transactionType;
    data['amount'] = amount;
    data['date'] = date;
    data['description'] = description;
    if (rideDetails != null) {
      data['rideDetails'] = rideDetails!.toJson();
    }
    return data;
  }
}

class TransactionsModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPages": 1,
  "totalItems": 5,
  "hasNextPage": false,
  "hasPrevPage": false,
  "limit": 10
} 
*/

  int? currentPage;
  int? totalPages;
  int? totalItems;
  bool? hasNextPage;
  bool? hasPrevPage;
  int? limit;

  TransactionsModelDataPagination({
    this.currentPage,
    this.totalPages,
    this.totalItems,
    this.hasNextPage,
    this.hasPrevPage,
    this.limit,
  });
  TransactionsModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPages = json['totalPages']?.toInt();
    totalItems = json['totalItems']?.toInt();
    hasNextPage = json['hasNextPage'];
    hasPrevPage = json['hasPrevPage'];
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPages'] = totalPages;
    data['totalItems'] = totalItems;
    data['hasNextPage'] = hasNextPage;
    data['hasPrevPage'] = hasPrevPage;
    data['limit'] = limit;
    return data;
  }
}

class TransactionsModelData {
/*
{
  "pagination": {
    "currentPage": 1,
    "totalPages": 1,
    "totalItems": 5,
    "hasNextPage": false,
    "hasPrevPage": false,
    "limit": 10
  },
  "transactions": [
    {
      "transactionId": "67e3bfad49bd87e7c20b7dab",
      "type": "ride",
      "userType": "Driver",
      "transactionType": "Credit",
      "amount": 12,
      "date": "2025-03-26T08:49:49.404Z",
      "description": "Amount added to wallet",
      "rideDetails": {
        "origin": {
          "name": "Toronto, ON, Canada",
          "coordinates": [
            -79.3831843
          ]
        },
        "destination": {
          "name": "Brampton, ON, Canada",
          "coordinates": [
            -79.7624177
          ]
        },
        "time": "2025-03-26T08:51:00.000Z",
        "date": "2025-03-26T00:00:00.000Z",
        "status": "",
        "otherParty": {
          "id": "676008013109b08b4eaec30b",
          "name": "UserFour",
          "profilePic": {
            "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
            "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
          },
          "role": "Rider"
        }
      }
    }
  ]
} 
*/

  TransactionsModelDataPagination? pagination;
  List<TransactionsModelDataTransactions>? transactions;

  TransactionsModelData({
    this.pagination,
    this.transactions,
  });
  TransactionsModelData.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? TransactionsModelDataPagination.fromJson(json['pagination']) : null;
  if (json['transactions'] != null) {
  final v = json['transactions'];
  final arr0 = <TransactionsModelDataTransactions>[];
  v.forEach((v) {
  arr0.add(TransactionsModelDataTransactions.fromJson(v));
  });
    transactions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    if (transactions != null) {
      final v = transactions;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['transactions'] = arr0;
    }
    return data;
  }
}

class TransactionsModel {
/*
{
  "status": true,
  "data": {
    "pagination": {
      "currentPage": 1,
      "totalPages": 1,
      "totalItems": 5,
      "hasNextPage": false,
      "hasPrevPage": false,
      "limit": 10
    },
    "transactions": [
      {
        "transactionId": "67e3bfad49bd87e7c20b7dab",
        "type": "ride",
        "userType": "Driver",
        "transactionType": "Credit",
        "amount": 12,
        "date": "2025-03-26T08:49:49.404Z",
        "description": "Amount added to wallet",
        "rideDetails": {
          "origin": {
            "name": "Toronto, ON, Canada",
            "coordinates": [
              -79.3831843
            ]
          },
          "destination": {
            "name": "Brampton, ON, Canada",
            "coordinates": [
              -79.7624177
            ]
          },
          "time": "2025-03-26T08:51:00.000Z",
          "date": "2025-03-26T00:00:00.000Z",
          "status": "",
          "otherParty": {
            "id": "676008013109b08b4eaec30b",
            "name": "UserFour",
            "profilePic": {
              "key": "usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg",
              "url": "https://green-pool-bucket.s3.ca-central-1.amazonaws.com/usersProfile/af8a3165-2f52-40aa-b4b1-a29c0123e4a7-compressed_image_cropper_01072F3A-172E-4F4E-A9D5-664F6F2E6BCC-23141-00000820C35D5FD4.jpg"
            },
            "role": "Rider"
          }
        }
      }
    ]
  }
} 
*/

  bool? status;
  TransactionsModelData? data;

  TransactionsModel({
    this.status,
    this.data,
  });
  TransactionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? TransactionsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
